import { CollectionPart } from '@/types/asmaulHusna';

const part03: CollectionPart = {
  id: 'part-03-tawakkal',
  partNumber: 3,
  title: 'Tawakkal & Bersandar kepada Allah',
  phaseTitle: 'Fase 3: Tawakkal dan Rezeki',
  asmaRange: [17, 24],
  estimatedReadMinutes: 24,
  introduction: 'Ya Allah, setelah aku memohon ketenangan jiwa dan jalan keluar dari segala kesempitan, kini aku memasuki fase tawakkal yang sesungguhnya. Aku menyerahkan seluruh urusanku kepada-Mu, karena Engkau adalah sebaik-baik Pemberi Rezeki, sebaik-baik Pembuka pintu, dan sebaik-baik Yang Mengetahui segala keadaanku.',
  quranEvidence: [
    { type: 'quran', reference: 'QS Hud [11]: 6', arabic: 'وَمَا مِن دَابَّةٍ فِي الْأَرْضِ إِلَّا عَلَى اللَّهِ رِزْقُهَا', transliteration: 'Wa ma min dabbatin fil-ardi illa alallahi rizquha', translationId: 'Dan tidak ada satu pun makhluk bergerak di bumi melainkan Allah-lah yang menanggung rezekinya.', verificationStatus: 'sahih' },
    { type: 'quran', reference: 'QS Ath-Thalaq [65]: 3', arabic: 'وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ', transliteration: 'Wa man yatawakkal alallahi fahuwa hasbuh', translationId: 'Dan barangsiapa bertawakal kepada Allah, niscaya Allah akan mencukupkan keperluan-nya.', verificationStatus: 'sahih' },
  ],
  hadithEvidence: [
    { type: 'hadith', reference: 'HR Tirmidzi no. 2344', arabic: 'لَوْ أَنَّكُمْ كُنْتُمْ تَوَكَّلُونَ عَلَى اللَّهِ حَقَّ تَوَكُّلِهِ لَرُزِقْتُمْ كَمَا يُرْزَقُ الطَّيْرُ', transliteration: 'Law annakum kuntum tawakkaluna alallahi haqqa tawakkulihi laruzigtum kama yurzaqut-tayr', translationId: 'Seandainya kalian benar-benar bertawakal kepada Allah dengan tawakal yang sesungguhnya, niscaya kalian akan diberi rezeki sebagaimana burung diberi rezeki.', verificationStatus: 'hasan' },
  ],
  items: [
    { number: 17, slug: 'ar-razzaq', nameArabic: 'الرَّزَّاقُ', transliteration: 'Ar-Razzaq', meaningId: 'Yang Maha Pemberi Rezeki', theme: ['rezeki','kecukupan','tawakkal'], explanation: 'Ar-Razzaq adalah nama Allah yang menunjukkan bahwa Dia adalah satu-satunya pemberi rezeki yang hakiki. Rezeki-Nya meliputi rezeki lahir berupa makanan, minuman, dan harta, serta rezeki batin berupa ilmu, iman, dan ketenangan hati.', dua: { arabic: 'يَا رَزَّاقُ، ارْزُقْنِي رِزْقًا حَلَالًا طَيِّبًا وَاسِعًا مُبَارَكًا مِنْ حَيْثُ لَا أَحْتَسِبُ، وَاجْعَلْنِي مِنَ الشَّاكِرِينَ عَلَى نِعَمِكَ', transliteration: 'Ya Razzaq, urzuqni rizqan halalan tayyiban wasian mubarakan min haythu la ahtasib, wajalni minasy-syakirin ala niamik', translationId: 'Wahai Yang Maha Pemberi Rezeki, berilah aku rezeki yang halal, baik, luas, dan berkah dari arah yang tidak aku sangka-sangka, dan jadikanlah aku termasuk orang-orang yang bersyukur atas nikmat-Mu.' }, evidence: [{ type: 'quran', reference: 'QS Adz-Dzariyat [51]: 58', arabic: 'إِنَّ اللَّهَ هُوَ الرَّزَّاقُ ذُو الْقُوَّةِ الْمَتِينُ', translationId: 'Sesungguhnya Allah, Dia-lah Yang Maha Pemberi Rezeki Yang Mempunyai Kekuatan lagi Sangat Kokoh.', verificationStatus: 'sahih' }], personalPlaceholders: ['rizq_goal','career_field'] },
    { number: 18, slug: 'al-fattah', nameArabic: 'الْفَتَّاحُ', transliteration: 'Al-Fattah', meaningId: 'Yang Maha Pembuka', theme: ['pembukaan','kemenangan','jalan-keluar'], explanation: 'Al-Fattah adalah nama Allah yang menunjukkan bahwa Dia membuka segala pintu yang tertutup: pintu rezeki, pintu rahmat, pintu taubat, pintu ilmu, dan pintu kemenangan. Tidak ada pintu yang dapat dibuka kecuali dengan izin-Nya.', dua: { arabic: 'يَا فَتَّاحُ، افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ وَرِزْقِكَ وَعِلْمِكَ وَتَوْفِيقِكَ، وَافْتَحْ لِي مِنْ أَمْرِي مَا أَغْلَقَتْهُ الْهُمُومُ وَالْغُمُومُ', transliteration: 'Ya Fattah, iftah li abwaba rahmatika wa rizqika wa ilmika wa tawfiqik', translationId: 'Wahai Yang Maha Pembuka, bukakanlah untukku pintu-pintu rahmat-Mu, rezeki-Mu, ilmu-Mu, dan taufik-Mu.' }, evidence: [{ type: 'quran', reference: 'QS Saba [34]: 26', arabic: 'وَهُوَ الْفَتَّاحُ الْعَلِيمُ', translationId: 'Dan Dia-lah Yang Maha Pembuka lagi Maha Mengetahui.', verificationStatus: 'sahih' }], personalPlaceholders: ['career_field','preferred_location'] },
    { number: 19, slug: 'al-alim', nameArabic: 'الْعَلِيمُ', transliteration: 'Al-Alim', meaningId: 'Yang Maha Mengetahui', theme: ['ilmu','pengawasan','kepercayaan'], explanation: 'Al-Alim adalah nama Allah yang menunjukkan ilmu-Nya yang sempurna dan menyeluruh. Dia mengetahui segala sesuatu: yang tersembunyi dan yang tampak, yang telah terjadi dan yang akan terjadi.', dua: { arabic: 'يَا عَلِيمُ، عَلِّمْنِي مَا يَنْفَعُنِي وَانْفَعْنِي بِمَا عَلَّمْتَنِي وَزِدْنِي عِلْمًا وَفَهْمًا وَحِكْمَةً', transliteration: 'Ya Alim, allimni ma yanfauni wanfani bima allamtani wa zidni ilman wa fahman wa hikmah', translationId: 'Wahai Yang Maha Mengetahui, ajarkanlah kepadaku apa yang bermanfaat bagiku dan tambahkanlah kepadaku ilmu, pemahaman, dan hikmah.' }, evidence: [{ type: 'quran', reference: 'QS Al-Baqarah [2]: 32', arabic: 'سُبْحَانَكَ لَا عِلْمَ لَنَا إِلَّا مَا عَلَّمْتَنَا', translationId: 'Maha Suci Engkau, tidak ada yang kami ketahui selain dari apa yang telah Engkau ajarkan kepada kami.', verificationStatus: 'sahih' }] },
    { number: 20, slug: 'al-qabidh', nameArabic: 'الْقَابِضُ', transliteration: 'Al-Qabidh', meaningId: 'Yang Maha Menyempitkan', theme: ['ujian','hikmah','penyerahan-diri'], explanation: 'Al-Qabidh adalah nama Allah yang menunjukkan bahwa Dia menyempitkan rezeki, hati, dan keadaan siapa yang Dia kehendaki dengan hikmah yang sempurna. Penyempitan-Nya bukan kezaliman, melainkan ujian atau persiapan untuk kelapangan yang lebih besar.', dua: { arabic: 'يَا قَابِضُ، إِذَا قَبَضْتَ عَلَيَّ فَاجْعَلْ قَبْضَكَ رَحْمَةً لِي وَتَطْهِيرًا وَتَكْفِيرًا لِذُنُوبِي، وَلَا تَقْبِضْ عَنِّي رَحْمَتَكَ أَبَدًا', transliteration: 'Ya Qabidh, idha qabadhta alayya fajal qadhaka rahmatan li wa tathiran wa takfiran li dhunubi', translationId: 'Wahai Yang Maha Menyempitkan, apabila Engkau menyempitkan keadaanku maka jadikanlah penyempitan-Mu itu sebagai rahmat, penyucian, dan penghapus dosa-dosaku.' }, evidence: [{ type: 'quran', reference: 'QS Al-Baqarah [2]: 245', arabic: 'وَاللَّهُ يَقْبِضُ وَيَبْسُطُ وَإِلَيْهِ تُرْجَعُونَ', translationId: 'Dan Allah menyempitkan dan melapangkan rezeki dan kepada-Nya-lah kamu dikembalikan.', verificationStatus: 'sahih' }] },
    { number: 21, slug: 'al-basit', nameArabic: 'الْبَاسِطُ', transliteration: 'Al-Basit', meaningId: 'Yang Maha Melapangkan', theme: ['kelapangan','rezeki','rahmat'], explanation: 'Al-Basit adalah nama Allah yang menunjukkan bahwa Dia melapangkan rezeki, hati, dan keadaan siapa yang Dia kehendaki. Setelah setiap penyempitan pasti ada kelapangan dari-Nya.', dua: { arabic: 'يَا بَاسِطُ، ابْسُطْ عَلَيَّ رِزْقَكَ وَرَحْمَتَكَ وَعَافِيَتَكَ، وَابْسُطْ لِي فِي عُمُرِي وَعِلْمِي وَعَمَلِي الصَّالِحِ', transliteration: 'Ya Basit, ubsut alayya rizqaka wa rahmataka wa afiyatak, wabsut li fi umuri wa ilmi wa amalis-salih', translationId: 'Wahai Yang Maha Melapangkan, lapangkanlah kepadaku rezeki-Mu, rahmat-Mu, dan kesehatan-Mu.' }, evidence: [{ type: 'quran', reference: 'QS Al-Baqarah [2]: 245', arabic: 'وَاللَّهُ يَقْبِضُ وَيَبْسُطُ', translationId: 'Dan Allah menyempitkan dan melapangkan rezeki.', verificationStatus: 'sahih' }], personalPlaceholders: ['rizq_goal'] },
    { number: 22, slug: 'al-khafidh', nameArabic: 'الْخَافِضُ', transliteration: 'Al-Khafidh', meaningId: 'Yang Maha Merendahkan', theme: ['keadilan','kekuasaan','tawadhu'], explanation: 'Al-Khafidh adalah nama Allah yang menunjukkan bahwa Dia merendahkan siapa yang Dia kehendaki dari para penguasa yang zalim dan orang-orang yang sombong. Tidak ada kemuliaan yang hakiki kecuali dari-Nya.', dua: { arabic: 'يَا خَافِضُ، اخْفِضْ كُلَّ مُتَكَبِّرٍ يُؤْذِينِي وَاخْفِضْ نَفْسِيَ الْأَمَّارَةَ بِالسُّوءِ وَاجْعَلْنِي مُتَوَاضِعًا لَكَ وَلِعِبَادِكَ', transliteration: 'Ya Khafidh, ikhfidh kulla mutakabbirin yudhini wakhfidh nafsiyyal-ammarata bis-su wajalni mutawadian laka wa li ibadik', translationId: 'Wahai Yang Maha Merendahkan, rendahkanlah setiap orang yang sombong yang menyakitiku dan jadikanlah aku rendah hati kepada-Mu.' }, evidence: [{ type: 'quran', reference: 'QS Al-Waqiah [56]: 3', arabic: 'خَافِضَةٌ رَّافِعَةٌ', translationId: 'Merendahkan satu golongan dan meninggikan golongan yang lain.', verificationStatus: 'sahih' }] },
    { number: 23, slug: 'ar-rafi', nameArabic: 'الرَّافِعُ', transliteration: 'Ar-Rafi', meaningId: 'Yang Maha Meninggikan', theme: ['kemuliaan','derajat','ketaatan'], explanation: 'Ar-Rafi adalah nama Allah yang menunjukkan bahwa Dia meninggikan derajat siapa yang Dia kehendaki: meninggikan para nabi dan rasul, meninggikan orang-orang beriman, dan meninggikan siapa yang merendahkan diri karena-Nya.', dua: { arabic: 'يَا رَافِعُ، ارْفَعْ دَرَجَتِي عِنْدَكَ وَعِنْدَ خَلْقِكَ بِالْإِيمَانِ وَالْعِلْمِ وَالْعَمَلِ الصَّالِحِ، وَارْفَعْ ذِكْرِي فِي الدُّنْيَا وَالْآخِرَةِ', transliteration: 'Ya Rafi, irfa darajati indaka wa inda khalqika bil-imani wal-ilmi wal-amalis-salih', translationId: 'Wahai Yang Maha Meninggikan, angkatlah derajatku di sisi-Mu dan di sisi makhluk-Mu dengan iman, ilmu, dan amal saleh.' }, evidence: [{ type: 'quran', reference: 'QS Al-Mujadilah [58]: 11', arabic: 'يَرْفَعِ اللَّهُ الَّذِينَ آمَنُوا مِنكُمْ وَالَّذِينَ أُوتُوا الْعِلْمَ دَرَجَاتٍ', translationId: 'Allah akan meninggikan orang-orang yang beriman di antaramu dan orang-orang yang diberi ilmu pengetahuan beberapa derajat.', verificationStatus: 'sahih' }], personalPlaceholders: ['career_field'] },
    { number: 24, slug: 'al-muizz', nameArabic: 'الْمُعِزُّ', transliteration: 'Al-Muizz', meaningId: 'Yang Maha Memberi Kemuliaan', theme: ['kemuliaan','izzah','ketaatan'], explanation: 'Al-Muizz adalah nama Allah yang menunjukkan bahwa Dia memberikan kemuliaan kepada siapa yang Dia kehendaki. Kemuliaan yang hakiki hanya datang dari-Nya. Siapa yang mencari kemuliaan dari selain Allah, maka ia akan mendapat kehinaan.', dua: { arabic: 'يَا مُعِزُّ، أَعِزَّنِي بِطَاعَتِكَ وَلَا تُذِلَّنِي بِمَعْصِيَتِكَ، وَأَعِزَّ الْإِسْلَامَ وَالْمُسْلِمِينَ وَاجْعَلْنِي مِنَ الْمُعَزَّزِينَ بِحُبِّكَ', transliteration: 'Ya Muizz, aizzani bitaatika wa la tudhillani bimasiyatik, wa aizzal-islama wal-muslimina', translationId: 'Wahai Yang Maha Memberi Kemuliaan, muliakanlah aku dengan ketaatan kepada-Mu dan jangan hinakan aku dengan kemaksiatan kepada-Mu, muliakanlah Islam dan kaum muslimin.' }, evidence: [{ type: 'quran', reference: 'QS Ali Imran [3]: 26', arabic: 'وَتُعِزُّ مَن تَشَاءُ وَتُذِلُّ مَن تَشَاءُ', translationId: 'Engkau muliakan siapa yang Engkau kehendaki dan Engkau hinakan siapa yang Engkau kehendaki.', verificationStatus: 'sahih' }], personalPlaceholders: ['family_names'] },
  ],
  matsurDuas: [
    { id: 'tawakkal-dua', title: 'Doa Tawakkal kepada Allah', source: 'HR Abu Dawud no. 5090, Tirmidzi no. 3426', dua: { arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ أَنْ أَضِلَّ أَوْ أُضَلَّ أَوْ أَزِلَّ أَوْ أُزَلَّ أَوْ أَظْلِمَ أَوْ أُظْلَمَ أَوْ أَجْهَلَ أَوْ يُجْهَلَ عَلَيَّ', transliteration: 'Allahumma inni audhu bika an adhilla aw udhalla aw azilla aw uzalla aw adhlima aw udhlama aw ajhala aw yujhala alayy', translationId: 'Ya Allah, aku berlindung kepada-Mu dari tersesat atau disesatkan, dari tergelincir atau digelincirkan, dari menzalimi atau dizalimi, dari berbuat bodoh atau diperlakukan dengan kebodohan.' }, virtue: 'Doa perlindungan yang diajarkan Nabi shallallahu alaihi wa sallam.' },
    { id: 'doa-rezeki-luas', title: 'Doa Memohon Kelapangan Rezeki', source: 'HR Tirmidzi no. 2344', dua: { arabic: 'اللَّهُمَّ ارْزُقْنِي رِزْقًا وَاسِعًا حَلَالًا طَيِّبًا مِنْ غَيْرِ كَدٍّ وَاسْتَجِبْ دُعَائِي مِنْ غَيْرِ رَدٍّ وَأَعُوذُ بِكَ مِنْ فَضِيحَةِ الدَّيْنِ وَغَلَبَةِ الْعَدُوِّ', transliteration: 'Allahumma-rzuqni rizqan wasi-an halalan tayyiban min ghayri kaddin wastajib du-a-i min ghayri raddin wa a-udzu bika min fadihati-d-dayni wa ghalabatil-aduww', translationId: 'Ya Allah, berilah aku rezeki yang luas, halal, dan baik tanpa kesulitan, kabulkanlah doaku tanpa penolakan, dan aku berlindung kepada-Mu dari aib hutang dan tekanan musuh.' }, virtue: 'Doa memohon rezeki yang luas tanpa kesulitan.' },
    { id: 'doa-tawakkal-burung', title: 'Doa Tawakkal Seperti Burung', source: 'HR Tirmidzi no. 2344, Ahmad no. 370', dua: { arabic: 'تَوَكَّلْتُ عَلَى اللَّهِ الَّذِي لَا إِلَهَ إِلَّا هُوَ، عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ', transliteration: 'Tawakkaltu alallahil-ladzi la ilaha illa huwa, alayhi tawakkaltu wa huwa rabbul-arsyil-azim', translationId: 'Aku bertawakal kepada Allah yang tidak ada Tuhan selain Dia. Kepada-Nya aku bertawakal dan Dia adalah Rabb Arsy yang agung.' }, virtue: 'Barangsiapa mengucapkannya maka akan dikatakan kepadanya: Engkau telah dicukupi, dilindungi, dan diberi petunjuk.' },
    { id: 'doa-keluar-rumah', title: 'Doa Keluar Rumah (Tawakkal)', source: 'HR Abu Dawud no. 5095, Tirmidzi no. 3426', dua: { arabic: 'بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ', transliteration: 'Bismillahi tawakkaltu alallahi la hawla wa la quwwata illa billah', translationId: 'Dengan nama Allah, aku bertawakal kepada Allah. Tidak ada daya dan kekuatan kecuali dengan pertolongan Allah.' }, virtue: 'Dikatakan kepadanya: Engkau telah dicukupi, dilindungi, dan dijauhkan darimu setan.' },
  ],
  closingDua: { arabic: 'اللَّهُمَّ يَا رَزَّاقُ يَا فَتَّاحُ يَا عَلِيمُ يَا قَابِضُ يَا بَاسِطُ يَا خَافِضُ يَا رَافِعُ يَا مُعِزُّ، ارْزُقْنَا وَافْتَحْ لَنَا وَعَلِّمْنَا وَأَعِزَّنَا بِطَاعَتِكَ', transliteration: 'Allahumma ya Razzaq ya Fattah ya Alim ya Qabidh ya Basit ya Khafidh ya Rafi ya Muizz, urzuqna waftah lana wa allimna wa aizzana bitaatik', translationId: 'Ya Allah, wahai Yang Maha Pemberi Rezeki, Yang Maha Pembuka, Yang Maha Mengetahui, Yang Maha Menyempitkan, Yang Maha Melapangkan, Yang Maha Merendahkan, Yang Maha Meninggikan, Yang Maha Memberi Kemuliaan, berilah kami rezeki, bukakanlah untuk kami, ajarkanlah kami, dan muliakanlah kami.' },
  closingParagraph: 'Ya Allah, dengan 8 nama-Mu yang agung dalam fase ini—Ar-Razzaq, Al-Fattah, Al-Alim, Al-Qabidh, Al-Basit, Al-Khafidh, Ar-Rafi, dan Al-Muizz—aku menyerahkan seluruh urusanku kepada-Mu dengan penuh tawakkal. Ya Allah, Engkau Ar-Razzaq, berilah aku rezeki halal sebesar 100 triliun rupiah atau lebih dari arah yang tidak aku sangka-sangka. Ya Allah, Engkau Al-Fattah, bukakanlah untukku pintu karier cybersecurity di Pekanbaru yang berkah dan bermanfaat bagi umat. Ya Allah, Engkau Al-Basit, lapangkanlah rezekiku dan lapangkanlah dadaku. Ya Allah, Engkau Ar-Rafi, tinggikanlah derajatku di sisi-Mu dan di sisi manusia. Ya Allah, sampaikan aku bersama istriku, orang tuaku, mertuaku, dan keluarga besarku untuk haji tahun 2026 bersama Ustadz Khalid Basalamah dan Ustadz Firanda Andirja. Aamiin ya Rabbal Aalamiin.',
};

export default part03;
