import { CollectionPart } from '@/types/asmaulHusna';

const part07: CollectionPart = {
  id: 'part-07-keesaan',
  partNumber: 7,
  title: 'Bersaksi Keesaan Allah',
  phaseTitle: 'Fase 7: Bersaksi Keesaan dan Kebenaran',
  asmaRange: [49, 56],
  estimatedReadMinutes: 22,
  introduction: 'Ya Allah, memasuki fase ketujuh ini aku bersaksi akan keesaan dan kebenaran-Mu. Engkau Al-Baits yang Maha Membangkitkan, Asy-Syahid yang Maha Menyaksikan, Al-Haqq yang Maha Benar, Al-Wakil yang Maha Memelihara urusan, Al-Qawiyy yang Mahakuat, Al-Matin yang Mahakokoh, Al-Waliyy yang Maha Melindungi, dan Al-Hamid yang Maha Terpuji.',
  quranEvidence: [
    { type: 'quran', reference: 'QS Al-Hajj [22]: 6', arabic: 'ذَلِكَ بِأَنَّ اللَّهَ هُوَ الْحَقُّ وَأَنَّهُ يُحْيِي الْمَوْتَى وَأَنَّهُ عَلَى كُلِّ شَيْءٍ قَدِيرٌ', translationId: 'Yang demikian itu karena sesungguhnya Allah, Dia-lah Yang Haq dan sesungguhnya Dia menghidupkan segala yang mati dan sesungguhnya Allah Mahakuasa atas segala sesuatu.', verificationStatus: 'sahih' },
    { type: 'quran', reference: 'QS Adz-Dzariyat [51]: 58', arabic: 'إِنَّ اللَّهَ هُوَ الرَّزَّاقُ ذُو الْقُوَّةِ الْمَتِينُ', translationId: 'Sesungguhnya Allah, Dia-lah Maha Pemberi Rezeki Yang Mempunyai Kekuatan lagi Sangat Kokoh.', verificationStatus: 'sahih' },
    { type: 'quran', reference: 'QS Ali Imran [3]: 150', arabic: 'بَلِ اللَّهُ مَوْلَاكُمْ وَهُوَ خَيْرُ النَّاصِرِينَ', translationId: 'Tetapi Allah-lah Pelindungmu, dan Dia-lah sebaik-baik Penolong.', verificationStatus: 'sahih' },
  ],
  hadithEvidence: [
    { type: 'hadith', reference: 'HR Bukhari no. 4563', arabic: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ', translationId: 'Cukuplah Allah bagi kami dan Dia sebaik-baik Pelindung.', verificationStatus: 'sahih' },
  ],
  items: [
    { number: 49, slug: 'al-baits', nameArabic: 'الْبَاعِثُ', transliteration: 'Al-Baits', meaningId: 'Yang Maha Membangkitkan', theme: ['kebangkitan', 'kehidupan', 'pembaruan'], explanation: 'Al-Baits adalah nama Allah yang menunjukkan bahwa Dia membangkitkan manusia dari kubur pada hari kiamat, membangkitkan para rasul untuk membimbing manusia, dan membangkitkan semangat serta kehidupan baru bagi hamba-Nya.', dua: { arabic: 'يَا بَاعِثُ، ابْعَثْنِي عَلَى الْإِسْلَامِ وَالْإِيمَانِ، وَابْعَثْ فِي قَلْبِي هِمَّةً عَالِيَةً وَعَزِيمَةً صَادِقَةً لِطَاعَتِكَ', transliteration: 'Ya Baits, ib-atsni alal-islami wal-iman, wab-ats fi qalbi himmatan aliyatan wa azimatan sadiqatan lita-atik', translationId: 'Wahai Yang Maha Membangkitkan, bangkitkanlah aku di atas Islam dan iman, dan bangkitkanlah dalam hatiku semangat yang tinggi dan tekad yang tulus untuk taat kepada-Mu.' }, evidence: [{ type: 'quran', reference: 'QS Al-Hajj [22]: 7', arabic: 'وَأَنَّ السَّاعَةَ آتِيَةٌ لَّا رَيْبَ فِيهَا وَأَنَّ اللَّهَ يَبْعَثُ مَن فِي الْقُبُورِ', translationId: 'Dan sesungguhnya hari kiamat itu pasti datang, tidak ada keraguan padanya, dan sesungguhnya Allah membangkitkan siapa yang di dalam kubur.', verificationStatus: 'sahih' }] },
    { number: 50, slug: 'asy-syahid', nameArabic: 'الشَّهِيدُ', transliteration: 'Asy-Syahid', meaningId: 'Yang Maha Menyaksikan', theme: ['persaksian', 'pengawasan', 'kebenaran'], explanation: 'Asy-Syahid adalah nama Allah yang menunjukkan bahwa Dia menyaksikan segala sesuatu yang terjadi di alam semesta ini. Tidak ada yang tersembunyi dari persaksian-Nya, baik yang lahir maupun yang batin.', dua: { arabic: 'يَا شَهِيدُ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا أَنْتَ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُكَ وَرَسُولُكَ، وَاجْعَلْنِي مِنَ الشُّهَدَاءِ بِالْحَقِّ يَوْمَ الْقِيَامَةِ', transliteration: 'Ya Syahid, asyhadu an la ilaha illa ant wa asyhadu anna Muhammadan abduka wa rasuluk, waj-alni minasy-syuhada-i bil-haqqi yawmal-qiyamah', translationId: 'Wahai Yang Maha Menyaksikan, aku bersaksi bahwa tiada Tuhan selain Engkau dan aku bersaksi bahwa Muhammad adalah hamba dan rasul-Mu, dan jadikanlah aku termasuk orang-orang yang bersaksi dengan kebenaran pada hari kiamat.' }, evidence: [{ type: 'quran', reference: 'QS Al-Maidah [5]: 117', arabic: 'وَكُنتَ أَنتَ الرَّقِيبَ عَلَيْهِمْ وَأَنتَ عَلَى كُلِّ شَيْءٍ شَهِيدٌ', translationId: 'Dan Engkau-lah Yang Mengawasi mereka. Dan Engkau Maha Menyaksikan atas segala sesuatu.', verificationStatus: 'sahih' }] },
    { number: 51, slug: 'al-haqq', nameArabic: 'الْحَقُّ', transliteration: 'Al-Haqq', meaningId: 'Yang Maha Benar', theme: ['kebenaran', 'keadilan', 'keyakinan'], explanation: 'Al-Haqq adalah nama Allah yang menunjukkan bahwa Dia adalah kebenaran yang mutlak. Dzat-Nya benar, sifat-sifat-Nya benar, perbuatan-Nya benar, firman-Nya benar, janji-Nya benar, dan perjumpaan dengan-Nya adalah benar.', dua: { arabic: 'يَا حَقُّ، ثَبِّتْنِي عَلَى الْحَقِّ وَاهْدِنِي إِلَى صِرَاطِكَ الْمُسْتَقِيمِ، وَأَرِنِي الْحَقَّ حَقًّا وَارْزُقْنِي اتِّبَاعَهُ وَأَرِنِي الْبَاطِلَ بَاطِلًا وَارْزُقْنِي اجْتِنَابَهُ', transliteration: 'Ya Haqq, tsabbitni alal-haqqi wahdini ila siratikal-mustaqim, wa arinal-haqqa haqqan warzuqnit-tiba-ahu wa arinal-batila batilan warzuqnij-tinabah', translationId: 'Wahai Yang Maha Benar, teguhkanlah aku di atas kebenaran dan tunjukilah aku ke jalan-Mu yang lurus, tunjukkanlah kepadaku kebenaran sebagai kebenaran dan karuniakanlah aku mengikutinya, dan tunjukkanlah kepadaku kebatilan sebagai kebatilan dan karuniakanlah aku menjauhinya.' }, evidence: [{ type: 'quran', reference: 'QS Al-Hajj [22]: 62', arabic: 'ذَلِكَ بِأَنَّ اللَّهَ هُوَ الْحَقُّ وَأَنَّ مَا يَدْعُونَ مِن دُونِهِ هُوَ الْبَاطِلُ', translationId: 'Yang demikian itu karena sesungguhnya Allah, Dia-lah Yang Haq dan sesungguhnya apa yang mereka seru selain Allah itulah yang batil.', verificationStatus: 'sahih' }] },
    { number: 52, slug: 'al-wakil', nameArabic: 'الْوَكِيلُ', transliteration: 'Al-Wakil', meaningId: 'Yang Maha Memelihara Urusan', theme: ['tawakkal', 'penyerahan-diri', 'kecukupan'], explanation: 'Al-Wakil adalah nama Allah yang menunjukkan bahwa Dia adalah sebaik-baik yang diserahi urusan. Siapa yang bertawakal kepada-Nya, maka Dia akan mencukupinya dan mengurus segala urusannya dengan sempurna.', dua: { arabic: 'يَا وَكِيلُ، أَنْتَ حَسْبِي وَنِعْمَ الْوَكِيلُ، تَوَكَّلْتُ عَلَيْكَ فِي جَمِيعِ أُمُورِي فَاكْفِنِي مَا أَهَمَّنِي وَمَا لَا أَهْتَمُّ بِهِ', transliteration: 'Ya Wakil, anta hasbi wa ni-mal-wakil, tawakkaltu alayka fi jami-i umuri fakfini ma ahammani wa ma la ahtammu bih', translationId: 'Wahai Yang Maha Memelihara Urusan, Engkau cukup bagiku dan sebaik-baik Pelindung, aku bertawakal kepada-Mu dalam seluruh urusanku maka cukupkanlah aku dari apa yang mengkhawatirkanku dan apa yang tidak aku perhatikan.' }, evidence: [{ type: 'quran', reference: 'QS Ali Imran [3]: 173', arabic: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ', translationId: 'Cukuplah Allah bagi kami dan Dia sebaik-baik Pelindung.', verificationStatus: 'sahih' }] },
    { number: 53, slug: 'al-qawiyy', nameArabic: 'الْقَوِيُّ', transliteration: 'Al-Qawiyy', meaningId: 'Yang Mahakuat', theme: ['kekuatan', 'pertolongan', 'keperkasaan'], explanation: 'Al-Qawiyy adalah nama Allah yang menunjukkan kekuatan-Nya yang sempurna dan tidak terbatas. Kekuatan-Nya tidak pernah berkurang, tidak pernah lemah, dan tidak ada yang dapat mengalahkan-Nya.', dua: { arabic: 'يَا قَوِيُّ، قَوِّنِي بِقُوَّتِكَ عَلَى طَاعَتِكَ وَعَلَى مُوَاجَهَةِ أَعْدَائِي وَأَعْدَاءِ دِينِكَ، وَلَا تَكِلْنِي إِلَى قُوَّتِي وَحَوْلِي', transliteration: 'Ya Qawiyy, qawwini biquwwatika ala ta-atika wa ala muwajahati a-da-i wa a-da-i dinik, wa la takilni ila quwwati wa hawli', translationId: 'Wahai Yang Mahakuat, kuatkanlah aku dengan kekuatan-Mu untuk taat kepada-Mu dan menghadapi musuh-musuhku dan musuh-musuh agama-Mu, dan jangan serahkan aku kepada kekuatan dan dayaku sendiri.' }, evidence: [{ type: 'quran', reference: 'QS Al-Hajj [22]: 74', arabic: 'إِنَّ اللَّهَ لَقَوِيٌّ عَزِيزٌ', translationId: 'Sesungguhnya Allah benar-benar Mahakuat lagi Mahaperkasa.', verificationStatus: 'sahih' }] },
    { number: 54, slug: 'al-matin', nameArabic: 'الْمَتِينُ', transliteration: 'Al-Matin', meaningId: 'Yang Mahakokoh', theme: ['kekuatan', 'keteguhan', 'kekokohan'], explanation: 'Al-Matin adalah nama Allah yang menunjukkan kekokohan kekuatan-Nya yang tidak pernah goyah, tidak pernah lemah, dan tidak pernah terpengaruh oleh apa pun. Kekuatan-Nya sangat kokoh dan sempurna.', dua: { arabic: 'يَا مَتِينُ، ثَبِّتْ قَلْبِي عَلَى دِينِكَ وَاجْعَلْ إِيمَانِي مَتِينًا لَا يَتَزَعْزَعُ بِالْفِتَنِ وَالشُّبُهَاتِ وَالشَّهَوَاتِ', transliteration: 'Ya Matin, tsabbit qalbi ala dinika waj-al imani matinan la yataza-za-u bil-fitani wasy-syubuhati wasy-syahawat', translationId: 'Wahai Yang Mahakokoh, teguhkanlah hatiku di atas agama-Mu dan jadikanlah imanku kokoh tidak tergoyahkan oleh fitnah, syubhat, dan syahwat.' }, evidence: [{ type: 'quran', reference: 'QS Adz-Dzariyat [51]: 58', arabic: 'إِنَّ اللَّهَ هُوَ الرَّزَّاقُ ذُو الْقُوَّةِ الْمَتِينُ', translationId: 'Sesungguhnya Allah, Dia-lah Maha Pemberi Rezeki Yang Mempunyai Kekuatan lagi Sangat Kokoh.', verificationStatus: 'sahih' }] },
    { number: 55, slug: 'al-waliyy', nameArabic: 'الْوَلِيُّ', transliteration: 'Al-Waliyy', meaningId: 'Yang Maha Melindungi', theme: ['perlindungan', 'pertolongan', 'kedekatan'], explanation: 'Al-Waliyy adalah nama Allah yang menunjukkan bahwa Dia adalah Pelindung, Penolong, dan Pendukung hamba-hamba-Nya yang beriman. Dia mengeluarkan mereka dari kegelapan kepada cahaya.', dua: { arabic: 'يَا وَلِيُّ، كُنْ لِي وَلِيًّا وَنَصِيرًا وَمُعِينًا، وَلَا تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ وَلَا أَقَلَّ مِنْ ذَلِكَ', transliteration: 'Ya Waliyy, kun li waliyyan wa nasiran wa mu-inan, wa la takilni ila nafsi tarfata aynin wa la aqalla min dzalik', translationId: 'Wahai Yang Maha Melindungi, jadilah bagiku pelindung, penolong, dan pendukung, dan jangan serahkan aku kepada diriku sendiri walau sekejap mata atau kurang dari itu.' }, evidence: [{ type: 'quran', reference: 'QS Al-Baqarah [2]: 257', arabic: 'اللَّهُ وَلِيُّ الَّذِينَ آمَنُوا يُخْرِجُهُم مِّنَ الظُّلُمَاتِ إِلَى النُّورِ', translationId: 'Allah Pelindung orang-orang yang beriman. Dia mengeluarkan mereka dari kegelapan kepada cahaya.', verificationStatus: 'sahih' }] },
    { number: 56, slug: 'al-hamid', nameArabic: 'الْحَمِيدُ', transliteration: 'Al-Hamid', meaningId: 'Yang Maha Terpuji', theme: ['pujian', 'syukur', 'kemuliaan'], explanation: 'Al-Hamid adalah nama Allah yang menunjukkan bahwa Dia Maha Terpuji dalam dzat, sifat, dan perbuatan-Nya. Segala pujian kembali kepada-Nya, baik dipuji oleh makhluk-Nya maupun tidak.', dua: { arabic: 'يَا حَمِيدُ، لَكَ الْحَمْدُ كَمَا يَنْبَغِي لِجَلَالِ وَجْهِكَ وَعَظِيمِ سُلْطَانِكَ، اجْعَلْنِي مِنَ الْحَامِدِينَ لَكَ فِي السَّرَّاءِ وَالضَّرَّاءِ', transliteration: 'Ya Hamid, lakal-hamdu kama yanbaghi lijalali wajhika wa azimi sultanik, ij-alni minal-hamidina laka fis-sarra-i wad-darra-', translationId: 'Wahai Yang Maha Terpuji, bagi-Mu segala pujian sebagaimana layak bagi kemuliaan wajah-Mu dan keagungan kekuasaan-Mu, jadikanlah aku termasuk orang-orang yang memuji-Mu dalam keadaan senang maupun susah.' }, evidence: [{ type: 'quran', reference: 'QS Ibrahim [14]: 1', arabic: 'إِلَى صِرَاطِ الْعَزِيزِ الْحَمِيدِ', translationId: 'Ke jalan Allah Yang Mahaperkasa lagi Maha Terpuji.', verificationStatus: 'sahih' }] },
  ],
  matsurDuas: [
    { id: 'doa-tawakkal', title: 'Doa Tawakkal kepada Allah', source: 'HR Bukhari no. 4563', dua: { arabic: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ', transliteration: 'Hasbunallahu wa ni-mal-wakil', translationId: 'Cukuplah Allah bagi kami dan Dia sebaik-baik Pelindung.' }, virtue: 'Kalimat yang diucapkan Ibrahim alaihis salam ketika dilempar ke api, dan diucapkan Nabi Muhammad shallallahu alaihi wa sallam ketika dikatakan bahwa musuh telah berkumpul.' },
    { id: 'doa-keteguhan', title: 'Doa Memohon Keteguhan Hati', source: 'HR Muslim no. 2654', dua: { arabic: 'يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَى دِينِكَ', transliteration: 'Ya Muqallibal-qulubi tsabbit qalbi ala dinik', translationId: 'Wahai Dzat yang membolak-balikkan hati, teguhkanlah hatiku di atas agama-Mu.' }, virtue: 'Doa yang paling sering dibaca Nabi shallallahu alaihi wa sallam karena hati manusia berada di antara dua jari dari jari-jari Allah.' },
    { id: 'doa-perlindungan-syirik', title: 'Doa Perlindungan dari Syirik', source: 'HR Ahmad no. 19606', dua: { arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ أَنْ أُشْرِكَ بِكَ وَأَنَا أَعْلَمُ وَأَسْتَغْفِرُكَ لِمَا لَا أَعْلَمُ', transliteration: 'Allahumma inni a-udzu bika an usyrika bika wa ana a-lamu wa astaghfiruka lima la a-lam', translationId: 'Ya Allah, aku berlindung kepada-Mu dari menyekutukan-Mu dalam keadaan aku mengetahui, dan aku memohon ampunan-Mu dari apa yang tidak aku ketahui.' }, virtue: 'Doa perlindungan dari syirik yang jelas maupun yang tersembunyi.' },
    { id: 'doa-kekuatan', title: 'Doa Memohon Kekuatan dari Allah', source: 'HR Muslim no. 2664', dua: { arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ وَالْجُبْنِ وَالْهَرَمِ وَالْبُخْلِ', transliteration: 'Allahumma inni a-udzu bika minal-ajzi wal-kasali wal-jubni wal-harami wal-bukhl', translationId: 'Ya Allah, aku berlindung kepada-Mu dari kelemahan, kemalasan, ketakutan, kepikunan, dan kekikiran.' }, virtue: 'Doa perlindungan dari 5 sifat yang melemahkan yang diajarkan Nabi shallallahu alaihi wa sallam.' },
  ],
  closingDua: { arabic: 'اللَّهُمَّ يَا بَاعِثُ يَا شَهِيدُ يَا حَقُّ يَا وَكِيلُ يَا قَوِيُّ يَا مَتِينُ يَا وَلِيُّ يَا حَمِيدُ، ابْعَثْنَا عَلَى الْإِيمَانِ وَثَبِّتْنَا عَلَى الْحَقِّ وَكُنْ لَنَا وَلِيًّا وَنَصِيرًا', transliteration: 'Allahumma ya Baits ya Syahid ya Haqq ya Wakil ya Qawiyy ya Matin ya Waliyy ya Hamid, ib-atsna alal-imani wa tsabbitna alal-haqqi wa kun lana waliyyan wa nasira', translationId: 'Ya Allah, wahai Yang Maha Membangkitkan, Yang Maha Menyaksikan, Yang Maha Benar, Yang Maha Memelihara Urusan, Yang Mahakuat, Yang Mahakokoh, Yang Maha Melindungi, Yang Maha Terpuji, bangkitkanlah kami di atas iman, teguhkanlah kami di atas kebenaran, dan jadilah bagi kami pelindung dan penolong.' },
  closingParagraph: 'Ya Allah, dengan 8 nama-Mu yang agung dalam fase ini—Al-Baits, Asy-Syahid, Al-Haqq, Al-Wakil, Al-Qawiyy, Al-Matin, Al-Waliyy, dan Al-Hamid—aku bersaksi bahwa tiada Tuhan selain Engkau dan aku bertawakal sepenuhnya kepada-Mu. Ya Allah, Engkau Al-Wakil, aku serahkan seluruh urusanku kepada-Mu termasuk hajatku untuk rezeki 100 triliun rupiah yang halal dan berkah. Ya Allah, Engkau Al-Qawiyy, kuatkanlah aku dalam menjalani karier cybersecurity di Pekanbaru yang berkah. Ya Allah, Engkau Al-Waliyy, jadilah pelindungku dan pelindung keluargaku dari segala keburukan. Ya Allah, Engkau Al-Haqq, tunjukkanlah kepadaku kebenaran dan jauhkanlah aku dari kebatilan. Ya Allah, sampaikan aku bersama istriku, orang tuaku, mertuaku, dan keluarga besarku untuk haji tahun 2026 bersama Ustadz Khalid Basalamah dan Ustadz Firanda Andirja. Aamiin ya Rabbal Aalamiin.',
};

export default part07;
