import { CollectionPart } from '@/types/asmaulHusna';

const part02: CollectionPart = {
  id: 'part-02-ketenangan',
  partNumber: 2,
  title: 'Ketenangan Jiwa, Jalan Keluar & Rahmat',
  phaseTitle: 'Fase 2: Ketenangan Jiwa dan Jalan Keluar',
  asmaRange: [9, 16],
  estimatedReadMinutes: 22,
  introduction: 'Yā Allāh, setelah aku bertaubat dan memohon ampunan-Mu di fase sebelumnya, kini aku memohon ketenangan jiwa yang hakiki. Ketenangan yang datang dari keyakinan yang kokoh bahwa Engkau adalah sebaik-baik pengatur urusan.',
  quranEvidence: [
    { type: 'quran', reference: 'QS Ath-Thalāq [65]: 2-3', arabic: 'وَمَن يَتَّقِ اللَّهَ يَجْعَل لَّهُ مَخْرَجًا وَيَرْزُقْهُ مِنْ حَيْثُ لَا يَحْتَسِبُ', transliteration: 'Wa man yattaqillāha yaj\'al lahu makhrajā. Wa yarzuqhu min ḥaytsu lā yaḥtasib', translationId: 'Barangsiapa bertakwa kepada Allah, niscaya Dia akan mengadakan jalan keluar baginya. Dan memberinya rezeki dari arah yang tidak disangka-sangkanya.', verificationStatus: 'sahih' },
    { type: 'quran', reference: 'QS Ar-Ra\'d [13]: 28', arabic: 'أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ', transliteration: 'Alā bidzikrillāhi taṭma\'innul-qulūb', translationId: 'Ingatlah, hanya dengan mengingat Allah hati menjadi tenteram.', verificationStatus: 'sahih' },
    { type: 'quran', reference: 'QS Asy-Syarḥ [94]: 5-6', arabic: 'فَإِنَّ مَعَ الْعُسْرِ يُسْرًا إِنَّ مَعَ الْعُسْرِ يُسْرًا', transliteration: 'Fa inna ma\'al-\'usri yusrā. Inna ma\'al-\'usri yusrā', translationId: 'Maka sesungguhnya bersama kesulitan ada kemudahan. Sesungguhnya bersama kesulitan ada kemudahan.', verificationStatus: 'sahih' },
  ],
  hadithEvidence: [
    { type: 'hadith', reference: 'HR Muslim no. 2999', transliteration: '\'Ajaban li\'amril-mu\'min...', translationId: 'Sungguh menakjubkan urusan orang beriman. Sesungguhnya semua urusannya adalah kebaikan. Jika ia mendapat kesenangan, ia bersyukur. Dan jika ia ditimpa kesusahan, ia bersabar.', verificationStatus: 'sahih' },
    { type: 'hadith', reference: 'HR Ahmad no. 2800, Tirmidzi no. 2516', translationId: 'Ketahuilah bahwa pertolongan itu bersama kesabaran, kelapangan itu bersama kesempitan, dan bersama kesulitan ada kemudahan.', verificationStatus: 'hasan' },
  ],
  items: [
    { number: 9, slug: 'al-jabbar', nameArabic: 'الْجَبَّارُ', transliteration: 'Al-Jabbār', meaningId: 'Yang Mahakuasa Memaksa / Maha Memperbaiki', theme: ['perbaikan', 'kekuatan', 'pertolongan'], explanation: 'Al-Jabbār menunjukkan tiga makna agung: Yang Mahatinggi, Yang Memaksa seluruh makhluk tunduk, dan Yang Memperbaiki keadaan hamba-hamba-Nya yang lemah.', dua: { arabic: 'يَا جَبَّارُ، يَا مَنْ يَجْبُرُ الْكَسِيرَ وَيُغْنِي الْفَقِيرَ، اجْبُرْ كَسْرَ قَلْبِي مِنْ كُلِّ خَيْبَةٍ وَإِحْبَاطٍ', transliteration: 'Yā Jabbār, yā man yajburul-kasīra wa yughnil-faqīr, ujbur kasra qalbī min kulli khaybatin wa iḥbāṭ', translationId: 'Wahai Yang Maha Memperbaiki, wahai Dzat yang memperbaiki yang patah dan mencukupkan yang fakir, perbaikilah kepatahan hatiku dari setiap kekecewaan dan keputusasaan.' }, evidence: [{ type: 'quran', reference: 'QS Al-Ḥasyr [59]: 23', translationId: 'Dialah Allah... Al-\'Azīz Al-Jabbār Al-Mutakabbir.', verificationStatus: 'sahih' }], personalPlaceholders: ['rizq_goal', 'career_field'] },
    { number: 10, slug: 'al-mutakabbir', nameArabic: 'الْمُتَكَبِّرُ', transliteration: 'Al-Mutakabbir', meaningId: 'Yang Maha Memiliki Kebesaran', theme: ['kebesaran', 'keagungan', 'tawadhu'], explanation: 'Al-Mutakabbir menunjukkan bahwa hanya Allah yang layak memiliki sifat kebesaran dan keagungan yang mutlak.', dua: { arabic: 'يَا مُتَكَبِّرُ، أَخْرِجِ الْكِبْرَ مِنْ قَلْبِي وَاجْعَلْنِي مُتَوَاضِعًا لَكَ خَاشِعًا لِعَظَمَتِكَ', transliteration: 'Yā Mutakabbir, akhrijil-kibra min qalbī waj\'alnī mutawāḍi\'an laka khāsyi\'an li\'aẓamatik', translationId: 'Wahai Yang Maha Memiliki Kebesaran, keluarkanlah kesombongan dari hatiku dan jadikanlah aku rendah hati kepada-Mu dan khusyuk kepada keagungan-Mu.' }, evidence: [{ type: 'hadith', reference: 'HR Muslim no. 2620', translationId: 'Kebesaran adalah selendang-Ku dan keagungan adalah sarung-Ku. Barangsiapa merebut salah satunya, Aku lemparkan ke neraka.', verificationStatus: 'sahih' }] },
    { number: 11, slug: 'al-khaliq', nameArabic: 'الْخَالِقُ', transliteration: 'Al-Khāliq', meaningId: 'Yang Maha Menciptakan', theme: ['penciptaan', 'takdir', 'hikmah'], explanation: 'Al-Khāliq menunjukkan bahwa Allah menentukan takdir sebelum menciptakan, menciptakan dari ketiadaan mutlak, dan mencipta dengan ilmu dan hikmah yang sempurna.', dua: { arabic: 'يَا خَالِقُ، اخْلُقْ فِي قَلْبِي نُورَ الْإِيمَانِ الَّذِي لَا يَنْطَفِئُ وَنُورَ الْيَقِينِ الَّذِي لَا يَتَزَعْزَعُ', transliteration: 'Yā Khāliq, ukhliq fī qalbī nūral-īmānilladhī lā yanṭafi\' wa nūral-yaqīnilladhī lā yataza\'za\'', translationId: 'Wahai Yang Maha Menciptakan, ciptakanlah dalam hatiku cahaya iman yang tidak pernah padam dan cahaya keyakinan yang tidak pernah goyah.' }, evidence: [{ type: 'quran', reference: 'QS Az-Zumar [39]: 62', arabic: 'اللَّهُ خَالِقُ كُلِّ شَيْءٍ', translationId: 'Allah adalah Pencipta segala sesuatu.', verificationStatus: 'sahih' }] },
    { number: 12, slug: 'al-bari', nameArabic: 'الْبَارِئُ', transliteration: 'Al-Bāri\'', meaningId: 'Yang Maha Mengadakan dari Tiada', theme: ['pengadaan', 'penyembuhan', 'pembaruan'], explanation: 'Al-Bāri\' berarti mengadakan dan mewujudkan dari ketiadaan. Juga bermakna menyembuhkan.', dua: { arabic: 'يَا بَارِئُ، ابْرَأْنِي مِنْ كُلِّ دَاءٍ وَسُقْمٍ وَابْرَأْ لِي طَرِيقًا جَدِيدًا إِلَى رِضَاكَ', transliteration: 'Yā Bāri\', ibra\'nī min kulli dā\'in wa suqmin wabra\' lī ṭarīqan jadīdan ilā riḍāk', translationId: 'Wahai Yang Maha Mengadakan, sembuhkanlah aku dari segala penyakit dan adakanlah untukku jalan baru menuju ridha-Mu.' }, evidence: [{ type: 'quran', reference: 'QS Al-Ḥasyr [59]: 24', arabic: 'هُوَ اللَّهُ الْخَالِقُ الْبَارِئُ الْمُصَوِّرُ', translationId: 'Dialah Allah Yang Menciptakan, Yang Mengadakan, Yang Membentuk Rupa.', verificationStatus: 'sahih' }] },
    { number: 13, slug: 'al-musawwir', nameArabic: 'الْمُصَوِّرُ', transliteration: 'Al-Muṣawwir', meaningId: 'Yang Maha Membentuk Rupa', theme: ['pembentukan', 'keindahan', 'keunikan'], explanation: 'Allah membentuk rupa dan memberikan ciri khas kepada setiap makhluk-Nya dengan keunikan tersendiri.', dua: { arabic: 'يَا مُصَوِّرُ، صَوِّرْنِي فِي أَحْسَنِ صُورَةٍ عِنْدَكَ: صُورَةِ الْعَبْدِ التَّقِيِّ النَّقِيِّ الصَّادِقِ الْمُخْلِصِ', transliteration: 'Yā Muṣawwir, ṣawwirnī fī aḥsani ṣūratin \'indak: ṣūratil-\'abdit-taqiyyin-naqiyyiṣ-ṣādiqil-mukhliṣ', translationId: 'Wahai Yang Maha Membentuk Rupa, bentuklah aku dalam sebaik-baik bentuk di sisi-Mu: bentuk hamba yang bertakwa, bersih, jujur, dan ikhlas.' }, evidence: [{ type: 'quran', reference: 'QS Āli \'Imrān [3]: 6', translationId: 'Dialah yang membentuk kamu dalam rahim sebagaimana yang Dia kehendaki.', verificationStatus: 'sahih' }] },
    { number: 14, slug: 'al-ghaffar', nameArabic: 'الْغَفَّارُ', transliteration: 'Al-Ghaffār', meaningId: 'Yang Maha Pengampun (Berulang-ulang)', theme: ['ampunan', 'istighfar', 'rezeki'], explanation: 'Al-Ghaffār menunjukkan bahwa Allah senantiasa mengampuni dosa-dosa hamba-Nya berulang kali tanpa batas selama hamba tersebut bertaubat.', dua: { arabic: 'يَا غَفَّارُ، اغْفِرْ لِي ذُنُوبِي كُلَّهَا صَغِيرَهَا وَكَبِيرَهَا أَوَّلَهَا وَآخِرَهَا سِرَّهَا وَعَلَانِيَتَهَا', transliteration: 'Yā Ghaffār, ighfir lī dzunūbī kullahā ṣaghīrahā wa kabīrahā awwalahā wa ākhirahā sirrahā wa \'alāniyatahā', translationId: 'Wahai Yang Maha Pengampun, ampunilah seluruh dosaku: yang kecil dan yang besar, yang pertama dan yang terakhir, yang tersembunyi dan yang terang-terangan.' }, evidence: [{ type: 'quran', reference: 'QS Nūḥ [71]: 10-12', translationId: 'Mohonlah ampunan kepada Tuhanmu, sesungguhnya Dia Maha Pengampun. Niscaya Dia akan menurunkan hujan yang lebat dan membantumu dengan harta dan anak-anak.', verificationStatus: 'sahih' }] },
    { number: 15, slug: 'al-qahhar', nameArabic: 'الْقَهَّارُ', transliteration: 'Al-Qahhār', meaningId: 'Yang Maha Menaklukkan', theme: ['kekuasaan', 'penaklukan', 'perlindungan'], explanation: 'Al-Qahhār menunjukkan bahwa Allah menaklukkan seluruh makhluk-Nya dengan kekuasaan-Nya yang sempurna.', dua: { arabic: 'يَا قَهَّارُ، اقْهَرْ نَفْسِيَ الْأَمَّارَةَ بِالسُّوءِ حَتَّى تَخْضَعَ لِأَمْرِكَ وَاقْهَرْ شَيْطَانِي حَتَّى لَا يَسْتَطِيعَ إِغْوَائِي', transliteration: 'Yā Qahhār, iqhar nafsiyyal-ammārata bis-sū\'i ḥattā takhḍa\'a li\'amrika waqhar syayṭānī ḥattā lā yastaṭī\'a ighwā\'ī', translationId: 'Wahai Yang Maha Menaklukkan, taklukkanlah nafsuku yang selalu menyuruh kepada keburukan hingga tunduk kepada perintah-Mu dan taklukkanlah setanku hingga tidak mampu menggodaku.' }, evidence: [{ type: 'quran', reference: 'QS Al-An\'ām [6]: 18', translationId: 'Dan Dialah yang berkuasa atas hamba-hamba-Nya. Dan Dialah Yang Mahabijaksana lagi Maha Mengetahui.', verificationStatus: 'sahih' }] },
    { number: 16, slug: 'al-wahhab', nameArabic: 'الْوَهَّابُ', transliteration: 'Al-Wahhāb', meaningId: 'Yang Maha Pemberi Karunia', theme: ['pemberian', 'karunia', 'kemurahan'], explanation: 'Al-Wahhāb menunjukkan bahwa Allah memberikan karunia tanpa imbalan, tanpa batas, tanpa lelah, dan tanpa syarat.', dua: { arabic: 'يَا وَهَّابُ، هَبْ لِي مِنْ لَدُنْكَ رَحْمَةً وَاسِعَةً وَعِلْمًا نَافِعًا وَرِزْقًا وَاسِعًا حَلَالًا طَيِّبًا مُبَارَكًا', transliteration: 'Yā Wahhāb, hab lī min ladunka raḥmatan wāsi\'atan wa \'ilman nāfi\'an wa rizqan wāsi\'an ḥalālan ṭayyiban mubārakan', translationId: 'Wahai Yang Maha Pemberi Karunia, karuniakanlah kepadaku dari sisi-Mu rahmat yang luas, ilmu yang bermanfaat, dan rezeki yang luas, halal, baik, dan berkah.' }, evidence: [{ type: 'quran', reference: 'QS Āli \'Imrān [3]: 8', arabic: 'رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً إِنَّكَ أَنتَ الْوَهَّابُ', translationId: 'Ya Rabb kami, jangan Engkau jadikan hati kami condong setelah Engkau beri petunjuk dan karuniakanlah kepada kami rahmat dari sisi-Mu. Sesungguhnya Engkau Maha Pemberi Karunia.', verificationStatus: 'sahih' }], personalPlaceholders: ['rizq_goal', 'career_field', 'hajj_umrah_target'] },
  ],
  matsurDuas: [
    { id: 'yunus-dua', title: 'Doa Nabi Yunus dalam Perut Ikan', source: 'QS Al-Anbiya [21]: 87', dua: { arabic: 'لَا إِلٰهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ', transliteration: 'La ilaha illa Anta, subhanaka inni kuntu minaz-zalimin', translationId: 'Tiada sesembahan yang berhak disembah selain Engkau, Mahasuci Engkau, sesungguhnya aku termasuk orang-orang yang zalim.' }, virtue: 'Tidak seorang muslim pun yang berdoa dengannya kecuali Allah akan mengabulkannya.' },
    { id: 'ibnu-masud', title: 'Doa Penghilang Segala Kegelisahan', source: 'HR Ahmad no. 3712', dua: { arabic: 'اللَّهُمَّ إِنِّي عَبْدُكَ وَابْنُ عَبْدِكَ وَابْنُ أَمَتِكَ نَاصِيَتِي بِيَدِكَ مَاضٍ فِيَّ حُكْمُكَ عَدْلٌ فِيَّ قَضَاؤُكَ', transliteration: 'Allahumma inni abduk, wabnu abdik, wabnu amatik, nasiyati biyadik, madin fiyya hukmuk, adlun fiyya qada-uk', translationId: 'Ya Allah, sesungguhnya aku adalah hamba-Mu, anak dari hamba laki-laki-Mu, anak dari hamba perempuan-Mu. Ubun-ubunku berada di tangan-Mu. Berlaku atasku hukum-Mu. Adil atasku ketetapan-Mu.' }, virtue: 'Tidaklah seorang hamba tertimpa kesedihan atau kegelisahan lalu berdoa dengannya kecuali Allah akan menghilangkan kesedihannya dan menggantinya dengan kegembiraan.' },
    { id: 'doa-ketenangan', title: 'Doa Memohon Ketenangan Hati', source: 'HR Muslim no. 2713', dua: { arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَالْعَجْزِ وَالْكَسَلِ وَالْبُخْلِ وَالْجُبْنِ وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ', transliteration: 'Allahumma inni a-udzu bika minal-hammi wal-hazani wal-ajzi wal-kasali wal-bukhli wal-jubni wa dala-id-dayni wa ghalabatir-rijal', translationId: 'Ya Allah, aku berlindung kepada-Mu dari kekhawatiran dan kesedihan, dari kelemahan dan kemalasan, dari kekikiran dan ketakutan, dari lilitan hutang dan tekanan orang.' }, virtue: 'Doa perlindungan dari 8 hal yang merusak ketenangan jiwa.' },
    { id: 'doa-jalan-keluar', title: 'Doa Memohon Jalan Keluar', source: 'HR Abu Dawud no. 1518', dua: { arabic: 'اللَّهُمَّ اجْعَلْ لِي مِنْ كُلِّ ضِيقٍ مَخْرَجًا وَمِنْ كُلِّ هَمٍّ فَرَجًا وَارْزُقْنِي مِنْ حَيْثُ لَا أَحْتَسِبُ', transliteration: 'Allahummaj-al li min kulli diqin makhrajan wa min kulli hammin farajan warzuqni min haythu la ahtasib', translationId: 'Ya Allah, jadikanlah untukku dari setiap kesempitan jalan keluar, dari setiap kekhawatiran kelapangan, dan berilah aku rezeki dari arah yang tidak aku sangka.' }, virtue: 'Doa yang mengandung janji Allah dalam QS Ath-Thalaq ayat 2-3.' },
  ],
  closingParagraph: 'Ya Allah, dengan 8 nama-Mu yang agung dalam fase ini—Al-Jabbar, Al-Mutakabbir, Al-Khaliq, Al-Bari, Al-Musawwir, Al-Ghaffar, Al-Qahhar, dan Al-Wahhab—aku bermunajat kepada-Mu memohon ketenangan jiwa yang hakiki dan jalan keluar dari segala kesempitan. Ya Allah, perbaikilah kepatahan hatiku dan bukakanlah jalan keluar dari setiap masalah yang mengimpitku. Ya Allah, karuniakanlah kepadaku rezeki 100 triliun rupiah yang halal dan berkah untuk kugunakan di jalan-Mu. Ya Allah, bukakanlah untukku pintu karier cybersecurity di Pekanbaru yang penuh berkah. Ya Allah, sampaikan aku bersama istriku, orang tuaku, mertuaku, dan keluarga besarku untuk haji tahun 2026 bersama Ustadz Khalid Basalamah dan Ustadz Firanda Andirja. Aamiin ya Rabbal Aalamiin.',
};

export default part02;
