import { CollectionPart } from '@/types/asmaulHusna';

const part04: CollectionPart = {
  id: 'part-04-keagungan',
  partNumber: 4,
  title: 'Tunduk Kepada Keagungan Allah',
  phaseTitle: 'Fase 4: Tunduk Kepada Keagungan',
  asmaRange: [25, 32],
  estimatedReadMinutes: 23,
  introduction: 'Ya Allah, memasuki fase keempat ini aku tunduk sepenuhnya kepada keagungan dan kekuasaan-Mu. Engkau Maha Mendengar setiap bisikan hati, Maha Melihat setiap gerak-gerik, Maha Memutuskan dengan adil, Maha Lembut dalam pertolongan-Mu, dan Maha Penyantun kepada hamba-hamba-Mu yang berdosa.',
  quranEvidence: [
    { type: 'quran', reference: 'QS Al-Hajj [22]: 61', arabic: 'وَأَنَّ اللَّهَ سَمِيعٌ بَصِيرٌ', translationId: 'Dan sesungguhnya Allah Maha Mendengar lagi Maha Melihat.', verificationStatus: 'sahih' },
    { type: 'quran', reference: 'QS Al-An\'am [6]: 103', arabic: 'لَا تُدْرِكُهُ الْأَبْصَارُ وَهُوَ يُدْرِكُ الْأَبْصَارَ وَهُوَ اللَّطِيفُ الْخَبِيرُ', translationId: 'Dia tidak dapat dicapai oleh penglihatan mata, sedang Dia dapat melihat segala penglihatan itu dan Dialah Yang Maha Halus lagi Maha Mengetahui.', verificationStatus: 'sahih' },
    { type: 'quran', reference: 'QS An-Nisa [4]: 40', arabic: 'إِنَّ اللَّهَ لَا يَظْلِمُ مِثْقَالَ ذَرَّةٍ', translationId: 'Sesungguhnya Allah tidak menzalimi seseorang walaupun sebesar zarrah.', verificationStatus: 'sahih' },
  ],
  hadithEvidence: [
    { type: 'hadith', reference: 'HR Muslim no. 2577', arabic: 'يَا عِبَادِي إِنِّي حَرَّمْتُ الظُّلْمَ عَلَى نَفْسِي وَجَعَلْتُهُ بَيْنَكُمْ مُحَرَّمًا فَلَا تَظَالَمُوا', translationId: 'Wahai hamba-hamba-Ku, sesungguhnya Aku telah mengharamkan kezaliman atas diri-Ku dan Aku jadikan kezaliman itu haram di antara kalian, maka janganlah kalian saling menzalimi.', verificationStatus: 'sahih' },
  ],
  items: [
    { number: 25, slug: 'al-mudzill', nameArabic: 'الْمُذِلُّ', transliteration: 'Al-Mudzill', meaningId: 'Yang Maha Menghinakan', theme: ['keadilan', 'kekuasaan', 'perlindungan'], explanation: 'Al-Mudzill adalah nama Allah yang menunjukkan bahwa Dia menghinakan siapa yang Dia kehendaki dari orang-orang yang sombong, zalim, dan kafir. Kehinaan yang hakiki hanya dari Allah, sebagaimana kemuliaan yang hakiki juga hanya dari-Nya.', dua: { arabic: 'يَا مُذِلُّ، أَذِلَّ نَفْسِيَ الْأَمَّارَةَ بِالسُّوءِ وَأَذِلَّ كُلَّ عَدُوٍّ يُرِيدُ بِي السُّوءَ، وَاجْعَلْنِي عَزِيزًا بِطَاعَتِكَ ذَلِيلًا بَيْنَ يَدَيْكَ', transliteration: 'Ya Mudzill, adzill nafsiyyal-ammarata bis-su-i wa adzill kulla aduwwin yuridu bis-su-a, waj-alni azizzan bita-atika dzalilan bayna yadayk', translationId: 'Wahai Yang Maha Menghinakan, hinakanlah nafsuku yang selalu menyuruh kepada keburukan dan hinakanlah setiap musuh yang menginginkan keburukan bagiku, jadikanlah aku mulia dengan ketaatan kepada-Mu dan hina di hadapan-Mu.' }, evidence: [{ type: 'quran', reference: 'QS Ali Imran [3]: 26', arabic: 'وَتُعِزُّ مَن تَشَاءُ وَتُذِلُّ مَن تَشَاءُ', translationId: 'Engkau muliakan siapa yang Engkau kehendaki dan Engkau hinakan siapa yang Engkau kehendaki.', verificationStatus: 'sahih' }] },
    { number: 26, slug: 'as-sami', nameArabic: 'السَّمِيعُ', transliteration: 'As-Sami', meaningId: 'Yang Maha Mendengar', theme: ['pendengaran', 'doa', 'kepercayaan'], explanation: 'As-Sami adalah nama Allah yang menunjukkan bahwa Dia mendengar segala sesuatu tanpa terkecuali: bisikan hati, ucapan lisan, doa yang dipanjatkan, dan segala suara di seluruh alam semesta.', dua: { arabic: 'يَا سَمِيعُ، اسْمَعْ دُعَائِي وَنِدَائِي وَتَضَرُّعِي إِلَيْكَ، وَاسْمَعْ مَا فِي قَلْبِي مِنَ الْحَاجَاتِ الَّتِي لَا أَسْتَطِيعُ التَّعْبِيرَ عَنْهَا بِلِسَانِي', transliteration: 'Ya Sami, isma du-a-i wa nida-i wa tadarru-i ilayk, wasma ma fi qalbi minal-hajati allati la astati-ut-ta-bira anha bilisani', translationId: 'Wahai Yang Maha Mendengar, dengarkanlah doaku, seruanku, dan permohonanku kepada-Mu, dan dengarkanlah apa yang ada dalam hatiku berupa hajat-hajat yang tidak mampu aku ungkapkan dengan lisanku.' }, evidence: [{ type: 'quran', reference: 'QS Al-Baqarah [2]: 127', arabic: 'رَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنتَ السَّمِيعُ الْعَلِيمُ', translationId: 'Ya Tuhan kami, terimalah dari kami. Sesungguhnya Engkaulah Yang Maha Mendengar lagi Maha Mengetahui.', verificationStatus: 'sahih' }] },
    { number: 27, slug: 'al-basir', nameArabic: 'الْبَصِيرُ', transliteration: 'Al-Basir', meaningId: 'Yang Maha Melihat', theme: ['penglihatan', 'pengawasan', 'keadilan'], explanation: 'Al-Basir adalah nama Allah yang menunjukkan bahwa Dia melihat segala sesuatu dengan penglihatan yang sempurna dan menyeluruh. Tidak ada yang tersembunyi dari penglihatan-Nya.', dua: { arabic: 'يَا بَصِيرُ، أَنْتَ تَرَى مَا لَا يَرَاهُ أَحَدٌ مِنْ حَالِي وَضَعْفِي وَحَاجَتِي، فَأَغِثْنِي بِرَحْمَتِكَ وَأَصْلِحْ أَحْوَالِي كُلَّهَا', transliteration: 'Ya Basir, anta tara ma la yarahu ahadun min hali wa da-fi wa hajati, fa-aghitsni birahmatika wa aslih ahwali kullaha', translationId: 'Wahai Yang Maha Melihat, Engkau melihat apa yang tidak dilihat siapa pun dari keadaanku, kelemahanku, dan hajatku, maka tolonglah aku dengan rahmat-Mu dan perbaikilah seluruh keadaanku.' }, evidence: [{ type: 'quran', reference: 'QS Al-Isra [17]: 1', arabic: 'إِنَّهُ هُوَ السَّمِيعُ الْبَصِيرُ', translationId: 'Sesungguhnya Dia adalah Yang Maha Mendengar lagi Maha Melihat.', verificationStatus: 'sahih' }] },
    { number: 28, slug: 'al-hakam', nameArabic: 'الْحَكَمُ', transliteration: 'Al-Hakam', meaningId: 'Yang Maha Memutuskan Perkara', theme: ['keputusan', 'keadilan', 'hukum'], explanation: 'Al-Hakam adalah nama Allah yang menunjukkan bahwa Dia adalah satu-satunya Hakim yang memutuskan perkara dengan adil dan sempurna. Keputusan-Nya tidak dapat dibantah dan selalu mengandung hikmah.', dua: { arabic: 'يَا حَكَمُ، احْكُمْ بَيْنِي وَبَيْنَ مَنْ ظَلَمَنِي بِحُكْمِكَ الْعَدْلِ، وَاحْكُمْ فِي أَمْرِي كُلِّهِ بِمَا فِيهِ خَيْرٌ لِي فِي الدُّنْيَا وَالْآخِرَةِ', transliteration: 'Ya Hakam, uhkum bayni wa bayna man zalamani bihukmikal-adl, wahkum fi amri kullihi bima fihi khayrun li fid-dunya wal-akhirah', translationId: 'Wahai Yang Maha Memutuskan Perkara, putuskanlah antara aku dan orang yang menzalimiku dengan keputusan-Mu yang adil, dan putuskanlah seluruh urusanku dengan apa yang mengandung kebaikan bagiku di dunia dan akhirat.' }, evidence: [{ type: 'quran', reference: 'QS Al-An\'am [6]: 57', arabic: 'إِنِ الْحُكْمُ إِلَّا لِلَّهِ', translationId: 'Keputusan itu hanyalah kepunyaan Allah.', verificationStatus: 'sahih' }] },
    { number: 29, slug: 'al-adl', nameArabic: 'الْعَدْلُ', transliteration: 'Al-Adl', meaningId: 'Yang Maha Adil', theme: ['keadilan', 'keseimbangan', 'hak'], explanation: 'Al-Adl adalah nama Allah yang menunjukkan bahwa Dia Maha Adil dalam segala hal. Keadilan-Nya sempurna dan mutlak, tidak pernah zalim sedikit pun.', dua: { arabic: 'يَا عَدْلُ، أَنْتَ الَّذِي لَا تَظْلِمُ أَحَدًا، أَسْأَلُكَ أَنْ تُعْطِيَنِي حَقِّي وَأَنْ تَرُدَّ عَلَيَّ مَا أُخِذَ مِنِّي بِغَيْرِ حَقٍّ، وَأَنْ تَجْعَلَنِي مِنَ الْعَادِلِينَ', transliteration: 'Ya Adl, antal-ladzi la tazlimu ahadan, as-aluka an tu-tiyani haqqi wa an tarudda alayya ma ukhidza minni bighayri haqq, wa an taj-alani minal-adilina', translationId: 'Wahai Yang Maha Adil, Engkau yang tidak pernah menzalimi siapa pun, aku memohon kepada-Mu agar Engkau memberiku hakku dan mengembalikan apa yang diambil dariku tanpa hak, dan menjadikanku termasuk orang-orang yang adil.' }, evidence: [{ type: 'quran', reference: 'QS An-Nisa [4]: 40', arabic: 'إِنَّ اللَّهَ لَا يَظْلِمُ مِثْقَالَ ذَرَّةٍ', translationId: 'Sesungguhnya Allah tidak menzalimi seseorang walaupun sebesar zarrah.', verificationStatus: 'sahih' }] },
    { number: 30, slug: 'al-latif', nameArabic: 'اللَّطِيفُ', transliteration: 'Al-Latif', meaningId: 'Yang Maha Lembut', theme: ['kelembutan', 'kasih-sayang', 'pertolongan-tersembunyi'], explanation: 'Al-Latif menunjukkan dua makna agung: Yang Maha Lembut dalam memberikan pertolongan dan karunia-Nya, dan Yang Maha Mengetahui hal-hal yang sangat halus dan tersembunyi.', dua: { arabic: 'يَا لَطِيفُ، الْطُفْ بِي فِي أَمْرِي كُلِّهِ كَمَا لَطَفْتَ بِعِبَادِكَ الصَّالِحِينَ، وَيَسِّرْ لِي أُمُورِي بِلُطْفِكَ الْخَفِيِّ الَّذِي لَا يَعْلَمُهُ إِلَّا أَنْتَ', transliteration: 'Ya Latif, ultuf bi fi amri kullihi kama latafta bi-ibadikas-salihin, wa yassir li umuri bilutfikal-khafiyyilladzi la ya-lamuhu illa ant', translationId: 'Wahai Yang Maha Lembut, lembutkanlah urusanku semuanya sebagaimana Engkau telah berlaku lembut kepada hamba-hamba-Mu yang saleh, dan mudahkanlah urusanku dengan kelembutan-Mu yang tersembunyi.' }, evidence: [{ type: 'quran', reference: 'QS Yusuf [12]: 100', arabic: 'إِنَّ رَبِّي لَطِيفٌ لِّمَا يَشَاءُ', translationId: 'Sesungguhnya Tuhanku Maha Lembut terhadap apa yang Dia kehendaki.', verificationStatus: 'sahih' }] },
    { number: 31, slug: 'al-khabir', nameArabic: 'الْخَبِيرُ', transliteration: 'Al-Khabir', meaningId: 'Yang Maha Mengetahui Hakikat', theme: ['pengetahuan-hakikat', 'kepercayaan', 'penyerahan-diri'], explanation: 'Al-Khabir menunjukkan bahwa Allah mengetahui hakikat segala sesuatu secara mendalam. Berbeda dengan Al-Alim yang menunjukkan keluasan ilmu, Al-Khabir menunjukkan kedalaman ilmu-Nya tentang hakikat batin segala sesuatu.', dua: { arabic: 'يَا خَبِيرُ، أَنْتَ أَعْلَمُ بِحَالِي مِنِّي، وَأَنْتَ تَعْلَمُ مَا يُصْلِحُنِي وَمَا يُفْسِدُنِي، فَاخْتَرْ لِي مَا فِيهِ صَلَاحِي فِي الدُّنْيَا وَالْآخِرَةِ', transliteration: 'Ya Khabir, anta a-lamu bihali minni, wa anta ta-lamu ma yushlihuni wa ma yufsiduni, fakhtarli ma fihi salahi fid-dunya wal-akhirah', translationId: 'Wahai Yang Maha Mengetahui Hakikat, Engkau lebih mengetahui keadaanku daripada diriku sendiri, maka pilihlah untukku apa yang mengandung kebaikanku di dunia dan akhirat.' }, evidence: [{ type: 'quran', reference: 'QS Al-Mulk [67]: 14', arabic: 'أَلَا يَعْلَمُ مَنْ خَلَقَ وَهُوَ اللَّطِيفُ الْخَبِيرُ', translationId: 'Apakah Allah yang menciptakan itu tidak mengetahui? Dan Dia Maha Halus lagi Maha Mengetahui.', verificationStatus: 'sahih' }] },
    { number: 32, slug: 'al-halim', nameArabic: 'الْحَلِيمُ', transliteration: 'Al-Halim', meaningId: 'Yang Maha Penyantun', theme: ['kesabaran', 'kelembutan', 'ampunan'], explanation: 'Al-Halim menunjukkan bahwa Allah Maha Penyantun dan tidak tergesa-gesa dalam menghukum hamba-hamba-Nya yang berdosa. Dia memberikan kesempatan untuk bertaubat dan memperbaiki diri.', dua: { arabic: 'يَا حَلِيمُ، بِحِلْمِكَ الَّذِي لَمْ تُعَاجِلْنِي بِالْعُقُوبَةِ عَلَى ذُنُوبِي، أَسْأَلُكَ أَنْ تَمْنَحَنِي حِلْمًا وَصَبْرًا وَأَنَاةً فِي أُمُورِي كُلِّهَا', transliteration: 'Ya Halim, bihilmikal-ladzi lam tu-ajilni bil-uqubati ala dzunubi, as-aluka an tamnahani hilman wa sabran wa anatan fi umuri kullaha', translationId: 'Wahai Yang Maha Penyantun, dengan kesantunan-Mu yang tidak menyegerakan hukuman atas dosa-dosaku, aku memohon kepada-Mu agar Engkau menganugerahiku kesantunan, kesabaran, dan ketenangan dalam seluruh urusanku.' }, evidence: [{ type: 'quran', reference: 'QS Al-Baqarah [2]: 235', arabic: 'وَاعْلَمُوا أَنَّ اللَّهَ غَفُورٌ حَلِيمٌ', translationId: 'Dan ketahuilah bahwa Allah Maha Pengampun lagi Maha Penyantun.', verificationStatus: 'sahih' }] },
  ],
  matsurDuas: [
    { id: 'doa-keadilan', title: 'Doa Memohon Perlindungan dari Kezaliman', source: 'HR Muslim no. 2577', dua: { arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ أَنْ أَظْلِمَ أَوْ أُظْلَمَ', transliteration: 'Allahumma inni a-udzu bika min an azlima aw uzlam', translationId: 'Ya Allah, aku berlindung kepada-Mu dari berbuat zalim atau dizalimi.' }, virtue: 'Doa perlindungan dari kezaliman yang diajarkan Nabi shallallahu alaihi wa sallam.' },
    { id: 'doa-kelembutan', title: 'Doa Memohon Kelembutan Allah', source: 'HR Tirmidzi no. 3524', dua: { arabic: 'يَا لَطِيفُ أَسْأَلُكَ اللُّطْفَ فِيمَا جَرَتْ بِهِ الْمَقَادِيرُ', transliteration: 'Ya Latifu as-alukal-lutfa fima jarat bihil-maqadir', translationId: 'Wahai Yang Maha Lembut, aku memohon kelembutan-Mu dalam apa yang telah ditetapkan takdir.' }, virtue: 'Doa memohon kelembutan Allah dalam menghadapi takdir yang telah ditetapkan.' },
    { id: 'doa-sabar', title: 'Doa Memohon Kesabaran', source: 'QS Al-Baqarah [2]: 250', dua: { arabic: 'رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا وَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ', transliteration: 'Rabbana afrigh alayna sabran wa tsabbit aqdamana wansurna alal-qawmil-kafirin', translationId: 'Ya Tuhan kami, limpahkanlah kesabaran kepada kami, teguhkanlah pendirian kami, dan tolonglah kami terhadap orang-orang kafir.' }, virtue: 'Doa para tentara Thalut ketika menghadapi Jalut dan pasukannya.' },
    { id: 'doa-perlindungan-mata', title: 'Doa Perlindungan dari Pandangan Haram', source: 'HR Ahmad no. 25043', dua: { arabic: 'اللَّهُمَّ اصْرِفْ عَنِّي بَصَرِي عَمَّا حَرَّمْتَ وَافْتَحْ لِي أَبْوَابَ رَحْمَتِكَ', transliteration: 'Allahummassrif anni basari amma harramta waftah li abwaba rahmatik', translationId: 'Ya Allah, palingkanlah pandanganku dari apa yang Engkau haramkan dan bukakanlah untukku pintu-pintu rahmat-Mu.' }, virtue: 'Doa menjaga pandangan dari hal-hal yang diharamkan Allah.' },
  ],
  closingDua: { arabic: 'اللَّهُمَّ يَا سَمِيعُ يَا بَصِيرُ يَا حَكَمُ يَا عَدْلُ يَا لَطِيفُ يَا خَبِيرُ يَا حَلِيمُ، أَصْلِحْ أَحْوَالَنَا وَاهْدِنَا إِلَى صِرَاطِكَ الْمُسْتَقِيمِ', transliteration: 'Allahumma ya Sami ya Basir ya Hakam ya Adl ya Latif ya Khabir ya Halim, aslih ahwalana wahdina ila siratikal-mustaqim', translationId: 'Ya Allah, wahai Yang Maha Mendengar, Yang Maha Melihat, Yang Maha Memutuskan, Yang Maha Adil, Yang Maha Lembut, Yang Maha Mengetahui Hakikat, Yang Maha Penyantun, perbaikilah keadaan kami dan tunjukilah kami ke jalan-Mu yang lurus.' },
  closingParagraph: 'Ya Allah, dengan 8 nama-Mu yang agung dalam fase ini—Al-Mudzill, As-Sami, Al-Basir, Al-Hakam, Al-Adl, Al-Latif, Al-Khabir, dan Al-Halim—aku tunduk sepenuhnya kepada keagungan dan kekuasaan-Mu. Ya Allah, Engkau As-Sami, dengarkanlah doaku ini dan jangan Engkau tolak. Ya Allah, Engkau Al-Latif, lembutkanlah urusanku dalam mencapai rezeki 100 triliun rupiah yang halal dan berkah. Ya Allah, Engkau Al-Hakam, putuskanlah untukku karier cybersecurity di Pekanbaru yang terbaik. Ya Allah, Engkau Al-Halim, bersabarlah atas kekuranganku dan teruslah membimbingku. Ya Allah, sampaikan aku bersama istriku, orang tuaku, mertuaku, dan keluarga besarku untuk haji tahun 2026 bersama Ustadz Khalid Basalamah dan Ustadz Firanda Andirja. Aamiin ya Rabbal Aalamiin.',
};

export default part04;
