import { CollectionPart } from '@/types/asmaulHusna';

const part01: CollectionPart = {
  id: 'part-01-taubat',
  partNumber: 1,
  title: 'Pembukaan dan Taubat Total',
  phaseTitle: 'Fase 1: Taubat Total dan Pembersihan Hati',
  asmaRange: [1, 8],
  estimatedReadMinutes: 25,
  introduction: 'Yā Allāh, sebelum aku memohon apa pun kepada-Mu, aku sadar bahwa dosa-dosaku adalah penghalang terbesar antara diriku dan rahmat-Mu. Maka aku memulai doa ini dengan taubat yang sungguh-sungguh, dengan penyesalan yang mendalam, dan dengan tekad yang kuat untuk tidak mengulangi dosa-dosaku.',
  quranEvidence: [
    {
      type: 'quran',
      reference: 'QS Al-Baqarah [2]: 186',
      arabic: 'وَإِذَا سَأَلَكَ عِبَادِي عَنِّي فَإِنِّي قَرِيبٌ ۖ أُجِيبُ دَعْوَةَ الدَّاعِ إِذَا دَعَانِ',
      transliteration: 'Wa idzā sa\'alaka \'ibādī \'annī fa innī qarīb, ujību da\'watad-dā\'i idzā da\'āni',
      translationId: 'Dan apabila hamba-hamba-Ku bertanya kepadamu tentang Aku, maka sesungguhnya Aku dekat. Aku kabulkan permohonan orang yang berdoa apabila dia berdoa kepada-Ku.',
      verificationStatus: 'sahih',
    },
    {
      type: 'quran',
      reference: 'QS Ghāfir [40]: 60',
      arabic: 'وَقَالَ رَبُّكُمُ ادْعُونِي أَسْتَجِبْ لَكُمْ',
      transliteration: 'Wa qāla Rabbukumud\'ūnī astajib lakum',
      translationId: 'Dan Tuhanmu berfirman: Berdoalah kepada-Ku, niscaya akan Aku perkenankan bagimu.',
      verificationStatus: 'sahih',
    },
    {
      type: 'quran',
      reference: 'QS Al-A\'rāf [7]: 180',
      arabic: 'وَلِلَّهِ الْأَسْمَاءُ الْحُسْنَىٰ فَادْعُوهُ بِهَا',
      transliteration: 'Wa lillāhil-asmā\'ul-ḥusnā fad\'ūhu bihā',
      translationId: 'Dan Allah memiliki Asmā\'ul Ḥusnā (nama-nama yang terbaik), maka bermohonlah kepada-Nya dengan menyebut nama-nama itu.',
      verificationStatus: 'sahih',
    },
    {
      type: 'quran',
      reference: 'QS Az-Zumar [39]: 53',
      arabic: 'قُلْ يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنفُسِهِمْ لَا تَقْنَطُوا مِن رَّحْمَةِ اللَّهِ',
      transliteration: 'Qul yā \'ibādiyalladhīna asrafū \'alā anfusihim lā taqnaṭū mir-raḥmatillāh',
      translationId: 'Katakanlah: Wahai hamba-hamba-Ku yang melampaui batas terhadap diri mereka sendiri, janganlah kamu berputus asa dari rahmat Allah.',
      verificationStatus: 'sahih',
    },
  ],
  hadithEvidence: [
    {
      type: 'hadith',
      reference: 'HR Abu Dawud no. 1488, Tirmidzi no. 3556',
      arabic: 'إِنَّ اللَّهَ حَيِيٌّ كَرِيمٌ يَسْتَحِي إِذَا رَفَعَ الرَّجُلُ إِلَيْهِ يَدَيْهِ أَنْ يَرُدَّهُمَا صِفْرًا خَائِبَتَيْنِ',
      transliteration: 'Innallāha ḥayyiyyun karīmun yastaḥyī idzā rafa\'ar-rajulu ilayhi yadayhi an yaruddahumā ṣifran khā\'ibatayn',
      translationId: 'Sesungguhnya Allah Maha Pemalu dan Maha Mulia. Dia malu apabila seorang hamba mengangkat kedua tangannya kepada-Nya, lalu Dia mengembalikannya dalam keadaan kosong dan kecewa.',
      verificationStatus: 'hasan',
    },
    {
      type: 'hadith',
      reference: 'HR Bukhari no. 2736, Muslim no. 2677',
      arabic: 'إِنَّ لِلَّهِ تِسْعَةً وَتِسْعِينَ اسْمًا مِائَةً إِلَّا وَاحِدًا مَنْ أَحْصَاهَا دَخَلَ الْجَنَّةَ',
      transliteration: 'Inna lillāhi tis\'atan wa tis\'īna isman mi\'atan illā wāḥidan man aḥṣāhā dakhalal-jannah',
      translationId: 'Sesungguhnya Allah memiliki 99 nama, seratus kurang satu. Barangsiapa yang menghafalnya, maka ia akan masuk surga.',
      verificationStatus: 'sahih',
    },
  ],
  items: [
    {
      number: 1,
      slug: 'ar-rahman',
      nameArabic: 'الرَّحْمٰنُ',
      transliteration: 'Ar-Raḥmān',
      meaningId: 'Yang Maha Pengasih',
      theme: ['rahmah', 'harapan', 'kasih-sayang'],
      explanation: 'Ar-Raḥmān adalah nama Allah yang menunjukkan sifat kasih sayang-Nya yang sangat luas dan intensif, meliputi seluruh makhluk tanpa terkecuali di dunia ini. Kasih sayang Ar-Raḥmān bersifat umum dan mencakup pemberian nikmat kehidupan, rezeki, kesehatan, dan segala kebutuhan dasar makhluk.',
      dua: {
        arabic: 'يَا رَحْمٰنُ، يَا مَنْ وَسِعَتْ رَحْمَتُهُ كُلَّ شَيْءٍ، يَا مَنْ رَحْمَتُهُ سَبَقَتْ غَضَبَهُ، أَسْأَلُكَ بِرَحْمَتِكَ الَّتِي وَسِعَتْ كُلَّ شَيْءٍ أَنْ تَرْحَمَنِي رَحْمَةً وَاسِعَةً عَظِيمَةً تَسَعُنِي وَتَسَعُ ذُنُوبِي وَخَطَايَايَ مَهْمَا كَثُرَتْ وَعَظُمَتْ',
        transliteration: 'Yā Raḥmān, yā man wasi\'at raḥmatuhu kulla syay\', yā man raḥmatuhu sabaqat ghaḍabah, as\'aluka biraḥmatikal-latī wasi\'at kulla syay\'in an tarḥamanī raḥmatan wāsi\'atan \'aẓīmatan tasa\'unī wa tasa\'u dzunūbī wa khaṭāyāya mahmā katsurat wa \'aẓumat',
        translationId: 'Wahai Yang Maha Pengasih, wahai Dzat yang rahmat-Nya meliputi segala sesuatu, wahai Dzat yang rahmat-Nya mendahului murka-Nya, aku memohon kepada-Mu dengan rahmat-Mu yang meliputi segala sesuatu agar Engkau merahmatiku dengan rahmat yang luas dan agung yang mencukupiku dan mencakup dosa-dosa serta kesalahan-kesalahanku betapa pun banyak dan besarnya.',
      },
      evidence: [
        { type: 'quran', reference: 'QS Al-A\'rāf [7]: 156', arabic: 'وَرَحْمَتِي وَسِعَتْ كُلَّ شَيْءٍ', transliteration: 'Wa raḥmatī wasi\'at kulla syay\'', translationId: 'Dan rahmat-Ku meliputi segala sesuatu.', verificationStatus: 'sahih' },
        { type: 'hadith', reference: 'HR Bukhari no. 6469, Muslim no. 2752', translationId: 'Sesungguhnya Allah menciptakan rahmat sebanyak seratus rahmat. Dia menahan di sisi-Nya 99 rahmat dan menurunkan ke seluruh makhluk-Nya satu rahmat saja.', verificationStatus: 'sahih' },
      ],
      personalPlaceholders: ['rizq_goal', 'family_names'],
    },
    {
      number: 2,
      slug: 'ar-rahim',
      nameArabic: 'الرَّحِيمُ',
      transliteration: 'Ar-Raḥīm',
      meaningId: 'Yang Maha Penyayang',
      theme: ['rahmah', 'akhirat', 'kekhususan'],
      explanation: 'Ar-Raḥīm adalah nama Allah yang menunjukkan kasih sayang-Nya yang khusus untuk orang-orang beriman, terutama di akhirat kelak. Jika Ar-Raḥmān bersifat umum di dunia untuk semua makhluk, maka Ar-Raḥīm bersifat khusus di akhirat berupa keselamatan dari azab, masuk surga, dan kenikmatan yang kekal abadi.',
      dua: {
        arabic: 'يَا رَحِيمُ، يَا مَنْ رَحْمَتُهُ خَاصَّةٌ بِالْمُؤْمِنِينَ، أَسْأَلُكَ أَنْ تَجْعَلَنِي مِنَ الْمُؤْمِنِينَ الَّذِينَ تَشْمَلُهُمْ رَحْمَتُكَ الْخَاصَّةُ فِي الدُّنْيَا وَالْآخِرَةِ',
        transliteration: 'Yā Raḥīm, yā man raḥmatuhu khāṣṣatun bil-mu\'minīn, as\'aluka an taj\'alanī minal-mu\'minīnalladhīna tasymaluhum raḥmatukal-khāṣṣatu fid-dunyā wal-ākhirah',
        translationId: 'Wahai Yang Maha Penyayang, wahai Dzat yang rahmat-Nya khusus bagi orang-orang beriman, aku memohon kepada-Mu agar Engkau menjadikanku termasuk orang-orang beriman yang tercakup dalam rahmat khusus-Mu di dunia dan di akhirat.',
      },
      evidence: [
        { type: 'quran', reference: 'QS Al-Aḥzāb [33]: 43', arabic: 'وَكَانَ بِالْمُؤْمِنِينَ رَحِيمًا', transliteration: 'Wa kāna bil-mu\'minīna raḥīmā', translationId: 'Dan Dia Maha Penyayang kepada orang-orang yang beriman.', verificationStatus: 'sahih' },
      ],
    },
    {
      number: 3,
      slug: 'al-malik',
      nameArabic: 'الْمَلِكُ',
      transliteration: 'Al-Malik',
      meaningId: 'Yang Maha Raja / Maha Merajai',
      theme: ['kekuasaan', 'kerajaan', 'pengaturan'],
      explanation: 'Al-Malik adalah nama Allah yang menunjukkan bahwa Dia adalah Pemilik kerajaan langit dan bumi secara hakiki dan mutlak. Kekuasaan-Nya sempurna, tidak terbatas, tidak membutuhkan siapa pun, dan seluruh makhluk membutuhkan-Nya.',
      dua: {
        arabic: 'يَا مَلِكُ، يَا مَالِكَ الْمُلْكِ، يَا مَنْ بِيَدِهِ مَلَكُوتُ كُلِّ شَيْءٍ، أَسْأَلُكَ أَنْ تُعْطِيَنِي مِنْ مُلْكِكَ مَا يُغْنِينِي عَنْ خَلْقِكَ',
        transliteration: 'Yā Malik, yā Mālikal-Mulk, yā man biyadihi malakūtu kulli syay\', as\'aluka an tu\'ṭiyanī min mulkika mā yughnīnī \'an khalqik',
        translationId: 'Wahai Yang Maha Raja, wahai Pemilik segala kerajaan, wahai Dzat yang di tangan-Nya kerajaan segala sesuatu, aku memohon kepada-Mu agar Engkau memberiku dari kerajaan-Mu apa yang menjadikanku tidak butuh kepada makhluk-Mu.',
      },
      evidence: [
        { type: 'quran', reference: 'QS Āli \'Imrān [3]: 26', arabic: 'قُلِ اللَّهُمَّ مَالِكَ الْمُلْكِ تُؤْتِي الْمُلْكَ مَن تَشَاءُ وَتَنزِعُ الْمُلْكَ مِمَّن تَشَاءُ', translationId: 'Katakanlah: Wahai Tuhan pemilik kekuasaan, Engkau berikan kekuasaan kepada siapa yang Engkau kehendaki dan Engkau cabut kekuasaan dari siapa yang Engkau kehendaki.', verificationStatus: 'sahih' },
      ],
    },
    {
      number: 4,
      slug: 'al-quddus',
      nameArabic: 'الْقُدُّوسُ',
      transliteration: 'Al-Quddūs',
      meaningId: 'Yang Mahasuci',
      theme: ['kesucian', 'kebersihan', 'tasbih'],
      explanation: 'Al-Quddūs adalah nama Allah yang menunjukkan kesucian-Nya yang mutlak dari segala kekurangan, aib, kelemahan, dan sifat-sifat yang tidak layak bagi keagungan-Nya.',
      dua: {
        arabic: 'يَا قُدُّوسُ، يَا مُنَزَّهًا عَنْ كُلِّ نَقْصٍ وَعَيْبٍ، أَسْأَلُكَ أَنْ تُقَدِّسَ قَلْبِي مِنْ كُلِّ شِرْكٍ جَلِيٍّ وَخَفِيٍّ، وَمِنْ كُلِّ رِيَاءٍ وَسُمْعَةٍ وَعُجْبٍ',
        transliteration: 'Yā Quddūs, yā munazzahan \'an kulli naqṣin wa \'ayb, as\'aluka an tuqaddisa qalbī min kulli syirkin jaliyyin wa khafiyy, wa min kulli riyā\'in wa sum\'atin wa \'ujb',
        translationId: 'Wahai Yang Mahasuci, wahai Dzat yang tersucikan dari segala kekurangan dan aib, aku memohon kepada-Mu agar Engkau mensucikan hatiku dari segala kesyirikan yang jelas maupun yang tersembunyi, dan dari segala riya, sum\'ah, dan ujub.',
      },
      evidence: [
        { type: 'quran', reference: 'QS Al-Ḥasyr [59]: 23', arabic: 'هُوَ اللَّهُ الَّذِي لَا إِلَٰهَ إِلَّا هُوَ الْمَلِكُ الْقُدُّوسُ السَّلَامُ', translationId: 'Dialah Allah, tidak ada Tuhan selain Dia. Dialah Yang Maha Raja, Yang Mahasuci, Yang Mahasejahtera.', verificationStatus: 'sahih' },
        { type: 'hadith', reference: 'HR Muslim no. 487', arabic: 'سُبُّوحٌ قُدُّوسٌ رَبُّ الْمَلَائِكَةِ وَالرُّوحِ', translationId: 'Mahasuci lagi Mahakudus, Tuhan para malaikat dan ruh (Jibril).', verificationStatus: 'sahih' },
      ],
    },
    {
      number: 5,
      slug: 'as-salam',
      nameArabic: 'السَّلَامُ',
      transliteration: 'As-Salām',
      meaningId: 'Yang Maha Memberi Keselamatan',
      theme: ['keselamatan', 'kedamaian', 'surga'],
      explanation: 'As-Salām memiliki dua makna utama: Allah adalah Dzat yang selamat dari segala kekurangan, dan Allah adalah sumber keselamatan dan kedamaian bagi seluruh makhluk-Nya.',
      dua: {
        arabic: 'يَا سَلَامُ، يَا مَنْ مِنْهُ السَّلَامُ وَإِلَيْهِ يَعُودُ السَّلَامُ، أَسْأَلُكَ السَّلَامَةَ فِي دِينِي وَدُنْيَايَ وَآخِرَتِي وَأَهْلِي وَمَالِي وَوَلَدِي',
        transliteration: 'Yā Salām, yā man minhus-salāmu wa ilayhi ya\'ūdus-salām, as\'alukas-salāmata fī dīnī wa dunyāya wa ākhiratī wa ahlī wa mālī wa waladī',
        translationId: 'Wahai Sumber Keselamatan, wahai Dzat yang dari-Nya keselamatan dan kepada-Nya kembali keselamatan, aku memohon kepada-Mu keselamatan dalam agamaku, duniaku, akhiratku, keluargaku, hartaku, dan anakku.',
      },
      evidence: [
        { type: 'quran', reference: 'QS Yūnus [10]: 25', arabic: 'وَاللَّهُ يَدْعُو إِلَىٰ دَارِ السَّلَامِ', translationId: 'Dan Allah menyeru (manusia) ke Dārus-Salām (surga).', verificationStatus: 'sahih' },
        { type: 'hadith', reference: 'HR Muslim no. 591', arabic: 'اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ', translationId: 'Ya Allah, Engkau adalah As-Salām, dan dari-Mu keselamatan. Mahasuci Engkau, wahai Pemilik keagungan dan kemuliaan.', verificationStatus: 'sahih' },
      ],
    },
    {
      number: 6,
      slug: 'al-mumin',
      nameArabic: 'الْمُؤْمِنُ',
      transliteration: 'Al-Mu\'min',
      meaningId: 'Yang Maha Pemberi Keamanan',
      theme: ['keamanan', 'iman', 'kepercayaan'],
      explanation: 'Al-Mu\'min memiliki beberapa makna: Pemberi Keamanan kepada hamba-hamba-Nya, Yang Membenarkan para rasul-Nya dengan mukjizat, dan Yang Dipercaya sepenuhnya karena tidak pernah mengingkari janji.',
      dua: {
        arabic: 'يَا مُؤْمِنُ، يَا مَنْ يُؤَمِّنُ خَوْفَ الْخَائِفِينَ، أَسْأَلُكَ أَنْ تُؤَمِّنَ خَوْفِي وَتُؤَمِّنَ رَوْعَتِي وَتَرْبِطَ عَلَى قَلْبِي بِالْإِيمَانِ وَالْيَقِينِ',
        transliteration: 'Yā Mu\'min, yā man yu\'amminu khawfal-khā\'ifīn, as\'aluka an tu\'ammina khawfī wa tu\'ammina raw\'atī wa tarbiṭa \'alā qalbī bil-īmāni wal-yaqīn',
        translationId: 'Wahai Yang Maha Pemberi Keamanan, wahai Dzat yang mengamankan ketakutan orang-orang yang takut, aku memohon kepada-Mu agar Engkau mengamankan ketakutanku, menenangkan kegentaranku, dan menguatkan hatiku dengan iman dan keyakinan.',
      },
      evidence: [
        { type: 'quran', reference: 'QS Al-An\'ām [6]: 82', arabic: 'الَّذِينَ آمَنُوا وَلَمْ يَلْبِسُوا إِيمَانَهُم بِظُلْمٍ أُولَٰئِكَ لَهُمُ الْأَمْنُ وَهُم مُّهْتَدُونَ', translationId: 'Orang-orang yang beriman dan tidak mencampuradukkan iman mereka dengan kezaliman, mereka itulah yang mendapat keamanan dan mereka itulah yang mendapat petunjuk.', verificationStatus: 'sahih' },
      ],
    },
    {
      number: 7,
      slug: 'al-muhaymin',
      nameArabic: 'الْمُهَيْمِنُ',
      transliteration: 'Al-Muhaymin',
      meaningId: 'Yang Maha Memelihara / Mengawasi',
      theme: ['pemeliharaan', 'pengawasan', 'penjagaan'],
      explanation: 'Al-Muhaymin adalah nama Allah yang menunjukkan bahwa Dia mengawasi segala sesuatu dengan ilmu-Nya yang sempurna, memelihara seluruh makhluk-Nya, dan menguasai segala sesuatu.',
      dua: {
        arabic: 'يَا مُهَيْمِنُ، يَا مَنْ هَيْمَنَ عَلَى كُلِّ شَيْءٍ بِعِلْمِهِ وَقُدْرَتِهِ وَحِكْمَتِهِ، أَسْأَلُكَ أَنْ تُهَيْمِنَ عَلَى قَلْبِي بِالْإِيمَانِ وَالتَّقْوَى وَالْيَقِينِ',
        transliteration: 'Yā Muhaymin, yā man haymana \'alā kulli syay\'in bi\'ilmih wa qudratihi wa ḥikmatih, as\'aluka an tuhaymina \'alā qalbī bil-īmāni wat-taqwā wal-yaqīn',
        translationId: 'Wahai Yang Maha Memelihara, wahai Dzat yang memelihara segala sesuatu dengan ilmu, kekuasaan, dan hikmah-Nya, aku memohon kepada-Mu agar Engkau memelihara hatiku dengan iman, takwa, dan keyakinan.',
      },
      evidence: [
        { type: 'quran', reference: 'QS Al-Ḥasyr [59]: 23', arabic: 'هُوَ اللَّهُ الَّذِي لَا إِلَٰهَ إِلَّا هُوَ الْمَلِكُ الْقُدُّوسُ السَّلَامُ الْمُؤْمِنُ الْمُهَيْمِنُ', translationId: 'Dialah Allah, tidak ada Tuhan selain Dia. Dialah Yang Maha Raja, Yang Mahasuci, Yang Mahasejahtera, Yang Maha Pemberi Keamanan, Yang Maha Memelihara.', verificationStatus: 'sahih' },
      ],
    },
    {
      number: 8,
      slug: 'al-aziz',
      nameArabic: 'الْعَزِيزُ',
      transliteration: 'Al-\'Azīz',
      meaningId: 'Yang Mahaperkasa / Maha Mulia',
      theme: ['kemuliaan', 'kekuatan', 'keperkasaan'],
      explanation: 'Al-\'Azīz memiliki tiga makna utama: Yang Mahakuat, Yang Mengalahkan segalanya, dan Yang Tidak Terjangkau. Kemuliaan yang hakiki hanya milik Allah.',
      dua: {
        arabic: 'يَا عَزِيزُ، يَا مَنْ عَزَّ كُلُّ شَيْءٍ بِعِزَّتِهِ، يَا مَنْ لَهُ الْعِزَّةُ جَمِيعًا، أَسْأَلُكَ أَنْ تُعِزَّنِي بِطَاعَتِكَ وَلَا تُذِلَّنِي بِمَعْصِيَتِكَ',
        transliteration: 'Yā \'Azīz, yā man \'azza kullu syay\'in bi\'izzatih, yā man lahul-\'izzatu jamī\'ā, as\'aluka an tu\'izzanī biṭā\'atika wa lā tudzillanī bima\'ṣiyatik',
        translationId: 'Wahai Yang Mahaperkasa, wahai Dzat yang segala sesuatu menjadi mulia dengan kemuliaan-Nya, wahai Dzat yang memiliki segala kemuliaan, aku memohon kepada-Mu agar Engkau memuliakanku dengan ketaatan kepada-Mu dan tidak menghinakanku dengan kemaksiatan kepada-Mu.',
      },
      evidence: [
        { type: 'quran', reference: 'QS Fāṭir [35]: 10', arabic: 'مَن كَانَ يُرِيدُ الْعِزَّةَ فَلِلَّهِ الْعِزَّةُ جَمِيعًا', translationId: 'Barangsiapa yang menghendaki kemuliaan, maka bagi Allah-lah segala kemuliaan.', verificationStatus: 'sahih' },
        { type: 'hadith', reference: 'HR Muslim no. 2588', arabic: 'مَنْ تَوَاضَعَ لِلَّهِ رَفَعَهُ اللَّهُ', translationId: 'Barangsiapa merendahkan diri karena Allah, niscaya Allah akan mengangkatnya.', verificationStatus: 'sahih' },
      ],
    },
  ],
  matsurDuas: [],
  closingParagraph: 'Yā Allāh, dengan 8 nama-Mu yang agung ini—Ar-Raḥmān, Ar-Raḥīm, Al-Malik, Al-Quddūs, As-Salām, Al-Mu\'min, Al-Muhaymin, dan Al-\'Azīz—aku bermunajat kepada-Mu dengan sepenuh kerendahan hati dan pengakuan atas segala kesalahanku. Jadikan taubat kami ini sebagai pembuka segala kebaikan yang akan kami mohon dalam doa ini.',
};

export default part01;
