import { CollectionPart } from '@/types/asmaulHusna';

const part05: CollectionPart = {
  id: 'part-05-mengagungkan',
  partNumber: 5,
  title: 'Mengagungkan Kebesaran Allah',
  phaseTitle: 'Fase 5: Mengagungkan Allah',
  asmaRange: [33, 40],
  estimatedReadMinutes: 22,
  introduction: 'Ya Allah, memasuki fase kelima ini aku mengagungkan kebesaran dan kemuliaan-Mu. Engkau Maha Agung yang tidak terjangkau oleh akal, Maha Pengampun yang menutupi aib hamba-Nya, Maha Mensyukuri amal sekecil apa pun, Mahatinggi di atas segala sesuatu, Mahabesar yang tiada bandingan, Maha Memelihara seluruh makhluk, Maha Pemberi Kecukupan, dan Maha Pembuat Perhitungan yang sempurna.',
  quranEvidence: [
    { type: 'quran', reference: 'QS Asy-Syura [42]: 11', arabic: 'لَيْسَ كَمِثْلِهِ شَيْءٌ وَهُوَ السَّمِيعُ الْبَصِيرُ', translationId: 'Tidak ada sesuatu pun yang serupa dengan Dia, dan Dia-lah Yang Maha Mendengar lagi Maha Melihat.', verificationStatus: 'sahih' },
    { type: 'quran', reference: 'QS Az-Zumar [39]: 53', arabic: 'إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا إِنَّهُ هُوَ الْغَفُورُ الرَّحِيمُ', translationId: 'Sesungguhnya Allah mengampuni dosa-dosa semuanya. Sesungguhnya Dia-lah Yang Maha Pengampun lagi Maha Penyayang.', verificationStatus: 'sahih' },
    { type: 'quran', reference: 'QS Saba [34]: 21', arabic: 'وَرَبُّكَ عَلَى كُلِّ شَيْءٍ حَفِيظٌ', translationId: 'Dan Tuhanmu Maha Memelihara segala sesuatu.', verificationStatus: 'sahih' },
  ],
  hadithEvidence: [
    { type: 'hadith', reference: 'HR Muslim no. 2687', arabic: 'مَنْ تَقَرَّبَ إِلَيَّ شِبْرًا تَقَرَّبْتُ إِلَيْهِ ذِرَاعًا', translationId: 'Barangsiapa mendekat kepada-Ku sejengkal, Aku mendekat kepadanya sehasta.', verificationStatus: 'sahih' },
  ],
  items: [
    { number: 33, slug: 'al-azim', nameArabic: 'الْعَظِيمُ', transliteration: 'Al-Azim', meaningId: 'Yang Maha Agung', theme: ['keagungan', 'kebesaran', 'tawadhu'], explanation: 'Al-Azim adalah nama Allah yang menunjukkan keagungan-Nya yang tidak terjangkau oleh akal manusia. Keagungan-Nya meliputi dzat, sifat, dan perbuatan-Nya. Tidak ada yang lebih agung dari-Nya.', dua: { arabic: 'يَا عَظِيمُ، أَنْتَ أَعْظَمُ مِنْ كُلِّ عَظِيمٍ، أَسْأَلُكَ بِعَظَمَتِكَ الَّتِي مَلَأَتِ السَّمَاوَاتِ وَالْأَرْضَ أَنْ تُعْظِمَ أَجْرِي وَتُعْظِمَ نَصِيبِي مِنْ رَحْمَتِكَ', transliteration: 'Ya Azim, anta a-zamu min kulli azim, as-aluka bi-azamatikal-lati mala-atis-samawati wal-ard an tu-zima ajri wa tu-zima nasibi min rahmatik', translationId: 'Wahai Yang Maha Agung, Engkau lebih agung dari segala yang agung, aku memohon kepada-Mu dengan keagungan-Mu yang memenuhi langit dan bumi agar Engkau membesarkan pahalaku dan membesarkan bagianku dari rahmat-Mu.' }, evidence: [{ type: 'quran', reference: 'QS Al-Baqarah [2]: 255', arabic: 'وَهُوَ الْعَلِيُّ الْعَظِيمُ', translationId: 'Dan Allah Mahatinggi lagi Mahabesar.', verificationStatus: 'sahih' }] },
    { number: 34, slug: 'al-ghafur', nameArabic: 'الْغَفُورُ', transliteration: 'Al-Ghafur', meaningId: 'Yang Maha Pengampun', theme: ['ampunan', 'rahmat', 'taubat'], explanation: 'Al-Ghafur adalah nama Allah yang menunjukkan bahwa Dia mengampuni dosa-dosa hamba-Nya dan menutupi aib mereka. Berbeda dengan Al-Ghaffar yang menunjukkan pengulangan, Al-Ghafur menunjukkan keluasan dan kesempurnaan ampunan-Nya.', dua: { arabic: 'يَا غَفُورُ، اغْفِرْ لِي مَا قَدَّمْتُ وَمَا أَخَّرْتُ وَمَا أَسْرَرْتُ وَمَا أَعْلَنْتُ وَمَا أَنْتَ أَعْلَمُ بِهِ مِنِّي، أَنْتَ الْمُقَدِّمُ وَأَنْتَ الْمُؤَخِّرُ', transliteration: 'Ya Ghafur, ighfir li ma qaddamtu wa ma akhkhartu wa ma asrartu wa ma a-lantu wa ma anta a-lamu bihi minni', translationId: 'Wahai Yang Maha Pengampun, ampunilah dosaku yang telah lalu dan yang akan datang, yang tersembunyi dan yang terang-terangan, dan yang Engkau lebih mengetahuinya daripada aku.' }, evidence: [{ type: 'quran', reference: 'QS Az-Zumar [39]: 53', arabic: 'إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا', translationId: 'Sesungguhnya Allah mengampuni dosa-dosa semuanya.', verificationStatus: 'sahih' }] },
    { number: 35, slug: 'asy-syakur', nameArabic: 'الشَّكُورُ', transliteration: 'Asy-Syakur', meaningId: 'Yang Maha Mensyukuri', theme: ['syukur', 'balasan', 'kebaikan'], explanation: 'Asy-Syakur adalah nama Allah yang menunjukkan bahwa Dia membalas amal kebaikan hamba-Nya dengan berlipat ganda, menerima amal yang sedikit dan membalasnya dengan pahala yang besar.', dua: { arabic: 'يَا شَكُورُ، اجْعَلْنِي مِنَ الشَّاكِرِينَ لِنِعَمِكَ، وَتَقَبَّلْ مِنِّي قَلِيلَ عَمَلِي وَأَعْظِمْ لِي أَجْرِي وَبَارِكْ لِي فِي عُمُرِي', transliteration: 'Ya Syakur, ij-alni minasy-syakirina li-ni-amik, wa taqabbal minni qalila amali wa a-zim li ajri wa barik li fi umuri', translationId: 'Wahai Yang Maha Mensyukuri, jadikanlah aku termasuk orang-orang yang bersyukur atas nikmat-Mu, terimalah amalku yang sedikit, besarkanlah pahalaku, dan berkahilah umurku.' }, evidence: [{ type: 'quran', reference: 'QS Fatir [35]: 30', arabic: 'إِنَّهُ غَفُورٌ شَكُورٌ', translationId: 'Sesungguhnya Dia Maha Pengampun lagi Maha Mensyukuri.', verificationStatus: 'sahih' }] },
    { number: 36, slug: 'al-aliyy', nameArabic: 'الْعَلِيُّ', transliteration: 'Al-Aliyy', meaningId: 'Yang Mahatinggi', theme: ['ketinggian', 'keagungan', 'kemuliaan'], explanation: 'Al-Aliyy adalah nama Allah yang menunjukkan ketinggian-Nya yang mutlak: tinggi dzat-Nya di atas Arsy, tinggi sifat-sifat-Nya yang sempurna, dan tinggi kekuasaan-Nya atas seluruh makhluk.', dua: { arabic: 'يَا عَلِيُّ، ارْفَعْنِي بِطَاعَتِكَ وَأَعْلِ دَرَجَتِي فِي الْجَنَّةِ، وَاجْعَلْنِي مِنَ الْمُقَرَّبِينَ إِلَيْكَ فِي الدُّنْيَا وَالْآخِرَةِ', transliteration: 'Ya Aliyy, irfa-ni bita-atika wa a-li darajati fil-jannah, waj-alni minal-muqarrabina ilayka fid-dunya wal-akhirah', translationId: 'Wahai Yang Mahatinggi, angkatlah aku dengan ketaatan kepada-Mu dan tinggikanlah derajatku di surga, dan jadikanlah aku termasuk orang-orang yang didekatkan kepada-Mu di dunia dan akhirat.' }, evidence: [{ type: 'quran', reference: 'QS Al-Baqarah [2]: 255', arabic: 'وَهُوَ الْعَلِيُّ الْعَظِيمُ', translationId: 'Dan Allah Mahatinggi lagi Mahabesar.', verificationStatus: 'sahih' }] },
    { number: 37, slug: 'al-kabir', nameArabic: 'الْكَبِيرُ', transliteration: 'Al-Kabir', meaningId: 'Yang Mahabesar', theme: ['kebesaran', 'keagungan', 'takbir'], explanation: 'Al-Kabir adalah nama Allah yang menunjukkan kebesaran-Nya yang mutlak dan sempurna. Dia lebih besar dari segala sesuatu, lebih besar dari segala yang dapat dibayangkan oleh akal manusia.', dua: { arabic: 'يَا كَبِيرُ، أَنْتَ أَكْبَرُ مِنْ كُلِّ هَمٍّ وَغَمٍّ وَمُصِيبَةٍ، أَسْأَلُكَ بِكِبْرِيَائِكَ أَنْ تُصَغِّرَ فِي عَيْنِي كُلَّ مَا أَخَافُهُ وَأَنْ تُكَبِّرَ فِي قَلْبِي حُبَّكَ وَخَشْيَتَكَ', transliteration: 'Ya Kabir, anta akbaru min kulli hammin wa ghammin wa musibah, as-aluka bikibriya-ika an tusaghghira fi ayni kulla ma akhafuhu wa an tukabbira fi qalbi hubbaka wa khasyiyatak', translationId: 'Wahai Yang Mahabesar, Engkau lebih besar dari segala kekhawatiran, kesedihan, dan musibah, aku memohon kepada-Mu dengan kebesaran-Mu agar Engkau mengecilkan di mataku segala yang aku takuti dan membesarkan di hatiku cinta dan takut kepada-Mu.' }, evidence: [{ type: 'quran', reference: 'QS Luqman [31]: 30', arabic: 'وَأَنَّ اللَّهَ هُوَ الْعَلِيُّ الْكَبِيرُ', translationId: 'Dan sesungguhnya Allah, Dia-lah Yang Mahatinggi lagi Mahabesar.', verificationStatus: 'sahih' }] },
    { number: 38, slug: 'al-hafiz', nameArabic: 'الْحَفِيظُ', transliteration: 'Al-Hafiz', meaningId: 'Yang Maha Memelihara', theme: ['pemeliharaan', 'penjagaan', 'perlindungan'], explanation: 'Al-Hafiz adalah nama Allah yang menunjukkan bahwa Dia memelihara seluruh makhluk-Nya, menjaga langit dan bumi dari kehancuran, dan memelihara amal-amal hamba-Nya tanpa ada yang terlewat.', dua: { arabic: 'يَا حَفِيظُ، احْفَظْنِي مِنْ بَيْنِ يَدَيَّ وَمِنْ خَلْفِي وَعَنْ يَمِينِي وَعَنْ شِمَالِي وَمِنْ فَوْقِي وَمِنْ تَحْتِي، وَاحْفَظْ لِي دِينِي وَأَهْلِي وَمَالِي', transliteration: 'Ya Hafiz, ihfazni min bayni yadayya wa min khalfi wa an yamini wa an syimali wa min fawqi wa min tahti, wahfaz li dini wa ahli wa mali', translationId: 'Wahai Yang Maha Memelihara, peliharalah aku dari depanku, belakangku, kananku, kiriku, atasku, dan bawahku, dan peliharalah agamaku, keluargaku, dan hartaku.' }, evidence: [{ type: 'quran', reference: 'QS Hud [11]: 57', arabic: 'إِنَّ رَبِّي عَلَى كُلِّ شَيْءٍ حَفِيظٌ', translationId: 'Sesungguhnya Tuhanku Maha Memelihara segala sesuatu.', verificationStatus: 'sahih' }] },
    { number: 39, slug: 'al-muqit', nameArabic: 'الْمُقِيتُ', transliteration: 'Al-Muqit', meaningId: 'Yang Maha Pemberi Kecukupan', theme: ['kecukupan', 'pemeliharaan', 'rezeki'], explanation: 'Al-Muqit adalah nama Allah yang menunjukkan bahwa Dia memberikan kecukupan kepada seluruh makhluk-Nya, baik kecukupan lahir berupa makanan dan rezeki, maupun kecukupan batin berupa iman dan hidayah.', dua: { arabic: 'يَا مُقِيتُ، أَقِتْنِي بِمَا يَكْفِينِي مِنْ حَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ، وَأَقِتْ قَلْبِي بِالْإِيمَانِ وَالْيَقِينِ', transliteration: 'Ya Muqit, aqitni bima yakfini min halalika an haramik wa aghnini bifadlika amman siwak, wa aqit qalbi bil-imani wal-yaqin', translationId: 'Wahai Yang Maha Pemberi Kecukupan, cukupkanlah aku dengan halal-Mu dari haram-Mu dan kayakanlah aku dengan karunia-Mu dari selain-Mu, dan cukupkanlah hatiku dengan iman dan keyakinan.' }, evidence: [{ type: 'quran', reference: 'QS An-Nisa [4]: 85', arabic: 'وَكَانَ اللَّهُ عَلَى كُلِّ شَيْءٍ مُّقِيتًا', translationId: 'Dan Allah Maha Kuasa atas segala sesuatu.', verificationStatus: 'sahih' }] },
    { number: 40, slug: 'al-hasib', nameArabic: 'الْحَسِيبُ', transliteration: 'Al-Hasib', meaningId: 'Yang Maha Pembuat Perhitungan', theme: ['perhitungan', 'kecukupan', 'tawakkal'], explanation: 'Al-Hasib memiliki dua makna: Yang Maha Mencukupi hamba-Nya sehingga tidak membutuhkan selain-Nya, dan Yang Maha Membuat Perhitungan atas segala amal perbuatan makhluk-Nya.', dua: { arabic: 'يَا حَسِيبُ، حَاسِبْنِي حِسَابًا يَسِيرًا وَلَا تُحَاسِبْنِي حِسَابًا عَسِيرًا، وَاكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَبِطَاعَتِكَ عَنْ مَعْصِيَتِكَ', transliteration: 'Ya Hasib, hasibni hisaban yasiran wa la tuhasibni hisaban asiran, wakfini bihalalika an haramika wa bita-atika an ma-siyatik', translationId: 'Wahai Yang Maha Pembuat Perhitungan, hisablah aku dengan hisab yang mudah dan jangan hisab aku dengan hisab yang sulit, dan cukupkanlah aku dengan halal-Mu dari haram-Mu dan dengan ketaatan kepada-Mu dari kemaksiatan kepada-Mu.' }, evidence: [{ type: 'quran', reference: 'QS An-Nisa [4]: 6', arabic: 'وَكَفَى بِاللَّهِ حَسِيبًا', translationId: 'Dan cukuplah Allah sebagai Pembuat Perhitungan.', verificationStatus: 'sahih' }], personalPlaceholders: ['rizq_goal'] },
  ],
  matsurDuas: [
    { id: 'doa-kecukupan', title: 'Doa Memohon Kecukupan dari Allah', source: 'HR Tirmidzi no. 3563', dua: { arabic: 'اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ', transliteration: 'Allahumma-kfini bihalalika an haramika wa aghnini bifadlika amman siwak', translationId: 'Ya Allah, cukupkanlah aku dengan halal-Mu dari haram-Mu dan kayakanlah aku dengan karunia-Mu dari selain-Mu.' }, virtue: 'Doa yang diajarkan Nabi shallallahu alaihi wa sallam untuk memohon kecukupan rezeki yang halal.' },
    { id: 'doa-perlindungan-6-arah', title: 'Doa Perlindungan dari 6 Arah', source: 'HR Abu Dawud no. 5074', dua: { arabic: 'اللَّهُمَّ احْفَظْنِي مِنْ بَيْنِ يَدَيَّ وَمِنْ خَلْفِي وَعَنْ يَمِينِي وَعَنْ شِمَالِي وَمِنْ فَوْقِي وَأَعُوذُ بِعَظَمَتِكَ أَنْ أُغْتَالَ مِنْ تَحْتِي', transliteration: 'Allahummahfazni min bayni yadayya wa min khalfi wa an yamini wa an syimali wa min fawqi wa a-udzu bi-azamatika an ughtala min tahti', translationId: 'Ya Allah, peliharalah aku dari depanku, belakangku, kananku, kiriku, atasku, dan aku berlindung dengan keagungan-Mu dari ditenggelamkan dari bawahku.' }, virtue: 'Doa perlindungan menyeluruh dari segala arah yang diajarkan Nabi shallallahu alaihi wa sallam.' },
    { id: 'doa-syukur', title: 'Doa Memohon Pertolongan untuk Bersyukur', source: 'HR Abu Dawud no. 1522', dua: { arabic: 'اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ', transliteration: 'Allahumma a-inni ala dzikrika wa syukrika wa husni ibadatik', translationId: 'Ya Allah, tolonglah aku untuk mengingat-Mu, bersyukur kepada-Mu, dan beribadah dengan baik kepada-Mu.' }, virtue: 'Doa yang diwasiatkan Nabi shallallahu alaihi wa sallam kepada Muadz bin Jabal radhiyallahu anhu untuk dibaca setiap selesai shalat.' },
    { id: 'doa-ampunan-luas', title: 'Doa Memohon Ampunan yang Luas', source: 'HR Bukhari no. 834, Muslim no. 2705', dua: { arabic: 'اللَّهُمَّ اغْفِرْ لِي مَا قَدَّمْتُ وَمَا أَخَّرْتُ وَمَا أَسْرَرْتُ وَمَا أَعْلَنْتُ وَمَا أَسْرَفْتُ وَمَا أَنْتَ أَعْلَمُ بِهِ مِنِّي', transliteration: 'Allahummagh-fir li ma qaddamtu wa ma akhkhartu wa ma asrartu wa ma a-lantu wa ma asraftu wa ma anta a-lamu bihi minni', translationId: 'Ya Allah, ampunilah dosaku yang telah lalu dan yang akan datang, yang tersembunyi dan yang terang-terangan, yang berlebihan, dan yang Engkau lebih mengetahuinya daripada aku.' }, virtue: 'Doa yang dibaca Nabi shallallahu alaihi wa sallam dalam shalat malam.' },
  ],
  closingDua: { arabic: 'اللَّهُمَّ يَا عَظِيمُ يَا غَفُورُ يَا شَكُورُ يَا عَلِيُّ يَا كَبِيرُ يَا حَفِيظُ يَا مُقِيتُ يَا حَسِيبُ، عَظِّمْ أُجُورَنَا وَاغْفِرْ ذُنُوبَنَا وَاحْفَظْنَا مِنْ كُلِّ سُوءٍ', transliteration: 'Allahumma ya Azim ya Ghafur ya Syakur ya Aliyy ya Kabir ya Hafiz ya Muqit ya Hasib, azzim ujurana waghfir dzunubana wahfazna min kulli su-', translationId: 'Ya Allah, wahai Yang Maha Agung, Yang Maha Pengampun, Yang Maha Mensyukuri, Yang Mahatinggi, Yang Mahabesar, Yang Maha Memelihara, Yang Maha Pemberi Kecukupan, Yang Maha Pembuat Perhitungan, besarkanlah pahala kami, ampunilah dosa-dosa kami, dan peliharalah kami dari segala keburukan.' },
  closingParagraph: 'Ya Allah, dengan 8 nama-Mu yang agung dalam fase ini—Al-Azim, Al-Ghafur, Asy-Syakur, Al-Aliyy, Al-Kabir, Al-Hafiz, Al-Muqit, dan Al-Hasib—aku mengagungkan kebesaran-Mu dan memohon perlindungan serta kecukupan dari-Mu. Ya Allah, Engkau Al-Azim, agungkanlah pahalaku dan agungkanlah rezekiku hingga mencapai 100 triliun rupiah yang halal dan berkah. Ya Allah, Engkau Al-Hafiz, peliharalah aku, keluargaku, hartaku, dan agamaku dari segala keburukan. Ya Allah, Engkau Al-Muqit, cukupkanlah aku dengan karier cybersecurity di Pekanbaru yang berkah. Ya Allah, Engkau Al-Hasib, hisablah aku dengan hisab yang mudah di hari kiamat. Ya Allah, sampaikan aku bersama istriku, orang tuaku, mertuaku, dan keluarga besarku untuk haji tahun 2026 bersama Ustadz Khalid Basalamah dan Ustadz Firanda Andirja. Aamiin ya Rabbal Aalamiin.',
};

export default part05;
