import { CollectionPart } from '@/types/asmaulHusna';

const part06: CollectionPart = {
  id: 'part-06-kemuliaan',
  partNumber: 6,
  title: 'Memohon Kemuliaan dan Kedekatan',
  phaseTitle: 'Fase 6: Memohon Kemuliaan',
  asmaRange: [41, 48],
  estimatedReadMinutes: 24,
  introduction: 'Ya Allah, memasuki fase keenam ini aku memohon kemuliaan dan kedekatan dengan-Mu. Engkau Al-Jalil yang Maha Mulia, Al-Karim yang Maha Pemurah, Ar-Raqib yang Maha Mengawasi, Al-Mujib yang Maha Mengabulkan doa, Al-Wasi yang Mahaluas rahmat-Nya, Al-Hakim yang Mahabijaksana, Al-Wadud yang Maha Mencintai, dan Al-Majid yang Maha Mulia lagi Maha Agung.',
  quranEvidence: [
    { type: 'quran', reference: 'QS Ar-Rahman [55]: 27', arabic: 'وَيَبْقَى وَجْهُ رَبِّكَ ذُو الْجَلَالِ وَالْإِكْرَامِ', translationId: 'Dan tetap kekal Wajah Tuhanmu yang mempunyai kebesaran dan kemuliaan.', verificationStatus: 'sahih' },
    { type: 'quran', reference: 'QS Hud [11]: 61', arabic: 'إِنَّ رَبِّي قَرِيبٌ مُّجِيبٌ', translationId: 'Sesungguhnya Tuhanku Maha Dekat lagi Maha Mengabulkan.', verificationStatus: 'sahih' },
    { type: 'quran', reference: 'QS Hud [11]: 90', arabic: 'إِنَّ رَبِّي رَحِيمٌ وَدُودٌ', translationId: 'Sesungguhnya Tuhanku Maha Penyayang lagi Maha Pencinta.', verificationStatus: 'sahih' },
  ],
  hadithEvidence: [
    { type: 'hadith', reference: 'HR Muslim no. 2675', arabic: 'إِنَّ اللَّهَ يُحِبُّ إِذَا عَمِلَ أَحَدُكُمْ عَمَلًا أَنْ يُتْقِنَهُ', translationId: 'Sesungguhnya Allah mencintai jika salah seorang dari kalian mengerjakan suatu pekerjaan, ia menyempurnakannya.', verificationStatus: 'hasan' },
  ],
  items: [
    { number: 41, slug: 'al-jalil', nameArabic: 'الْجَلِيلُ', transliteration: 'Al-Jalil', meaningId: 'Yang Maha Mulia', theme: ['kemuliaan', 'keagungan', 'kebesaran'], explanation: 'Al-Jalil adalah nama Allah yang menunjukkan kemuliaan dan keagungan-Nya yang sempurna. Kemuliaan-Nya meliputi seluruh sifat-sifat-Nya yang agung dan sempurna.', dua: { arabic: 'يَا جَلِيلُ، أَجِلَّنِي بِطَاعَتِكَ وَلَا تُهِنِّي بِمَعْصِيَتِكَ، وَأَكْرِمْنِي بِقُرْبِكَ وَلَا تُبْعِدْنِي بِذُنُوبِي', transliteration: 'Ya Jalil, ajillani bita-atika wa la tuhinnani bima-siyatik, wa akrimni biqurbika wa la tub-idni bidzunubi', translationId: 'Wahai Yang Maha Mulia, muliakanlah aku dengan ketaatan kepada-Mu dan jangan hinakan aku dengan kemaksiatan kepada-Mu, muliakanlah aku dengan kedekatan-Mu dan jangan jauhkan aku karena dosa-dosaku.' }, evidence: [{ type: 'quran', reference: 'QS Ar-Rahman [55]: 27', arabic: 'وَيَبْقَى وَجْهُ رَبِّكَ ذُو الْجَلَالِ وَالْإِكْرَامِ', translationId: 'Dan tetap kekal Wajah Tuhanmu yang mempunyai kebesaran dan kemuliaan.', verificationStatus: 'sahih' }] },
    { number: 42, slug: 'al-karim', nameArabic: 'الْكَرِيمُ', transliteration: 'Al-Karim', meaningId: 'Yang Maha Pemurah', theme: ['kemurahan', 'pemberian', 'kemuliaan'], explanation: 'Al-Karim adalah nama Allah yang menunjukkan kemurahan-Nya yang sempurna. Dia memberi tanpa diminta, memberi lebih dari yang diminta, tidak pernah mengungkit pemberian-Nya, dan tidak pernah menolak orang yang meminta.', dua: { arabic: 'يَا كَرِيمُ، أَكْرِمْنِي بِكَرَمِكَ الَّذِي لَا يَنْفَدُ وَلَا يَنْقَطِعُ، وَأَعْطِنِي مِنْ خَزَائِنِكَ الَّتِي لَا تَنْقُصُ بِالْعَطَاءِ', transliteration: 'Ya Karim, akrimni bikaramikal-ladzi la yanfadu wa la yanqati, wa a-tini min khaza-inikal-lati la tanqusu bil-ata-', translationId: 'Wahai Yang Maha Pemurah, muliakanlah aku dengan kemurahan-Mu yang tidak pernah habis dan tidak pernah terputus, dan berikanlah kepadaku dari perbendaharaan-Mu yang tidak berkurang dengan pemberian.' }, evidence: [{ type: 'quran', reference: 'QS Al-Infitar [82]: 6', arabic: 'يَا أَيُّهَا الْإِنسَانُ مَا غَرَّكَ بِرَبِّكَ الْكَرِيمِ', translationId: 'Wahai manusia, apakah yang telah memperdayakanmu terhadap Tuhanmu Yang Maha Pemurah?', verificationStatus: 'sahih' }], personalPlaceholders: ['rizq_goal'] },
    { number: 43, slug: 'ar-raqib', nameArabic: 'الرَّقِيبُ', transliteration: 'Ar-Raqib', meaningId: 'Yang Maha Mengawasi', theme: ['pengawasan', 'muraqabah', 'ihsan'], explanation: 'Ar-Raqib adalah nama Allah yang menunjukkan bahwa Dia mengawasi seluruh makhluk-Nya setiap saat tanpa lengah sedikit pun. Pengawasan-Nya meliputi segala gerak-gerik, ucapan, dan bahkan bisikan hati.', dua: { arabic: 'يَا رَقِيبُ، اجْعَلْنِي مُرَاقِبًا لَكَ فِي كُلِّ أَحْوَالِي، وَاجْعَلْ مُرَاقَبَتَكَ لِي سَبَبًا لِاسْتِقَامَتِي عَلَى طَاعَتِكَ', transliteration: 'Ya Raqib, ij-alni muraqiban laka fi kulli ahwali, waj-al muraqabataka li sababan li-istiqamati ala ta-atik', translationId: 'Wahai Yang Maha Mengawasi, jadikanlah aku selalu merasa diawasi oleh-Mu dalam segala keadaanku, dan jadikanlah pengawasan-Mu kepadaku sebagai sebab istiqamahku dalam ketaatan kepada-Mu.' }, evidence: [{ type: 'quran', reference: 'QS An-Nisa [4]: 1', arabic: 'إِنَّ اللَّهَ كَانَ عَلَيْكُمْ رَقِيبًا', translationId: 'Sesungguhnya Allah selalu menjaga dan mengawasimu.', verificationStatus: 'sahih' }] },
    { number: 44, slug: 'al-mujib', nameArabic: 'الْمُجِيبُ', transliteration: 'Al-Mujib', meaningId: 'Yang Maha Mengabulkan', theme: ['pengabulan', 'doa', 'kedekatan'], explanation: 'Al-Mujib adalah nama Allah yang menunjukkan bahwa Dia mengabulkan doa orang yang berdoa kepada-Nya dan memenuhi kebutuhan orang yang meminta kepada-Nya. Dia dekat dan selalu siap mengabulkan.', dua: { arabic: 'يَا مُجِيبُ، أَجِبْ دُعَائِي وَلَا تَرُدَّنِي خَائِبًا، وَأَعْطِنِي سُؤْلِي وَحَقِّقْ أَمَلِي وَرَجَائِي فِيكَ', transliteration: 'Ya Mujib, ajib du-a-i wa la taruddani kha-iban, wa a-tini su-li wa haqqiq amali wa raja-i fik', translationId: 'Wahai Yang Maha Mengabulkan, kabulkanlah doaku dan jangan kembalikan aku dalam keadaan kecewa, berikanlah permintaanku dan wujudkanlah harapan serta pengharapanku kepada-Mu.' }, evidence: [{ type: 'quran', reference: 'QS Hud [11]: 61', arabic: 'إِنَّ رَبِّي قَرِيبٌ مُّجِيبٌ', translationId: 'Sesungguhnya Tuhanku Maha Dekat lagi Maha Mengabulkan.', verificationStatus: 'sahih' }], personalPlaceholders: ['rizq_goal', 'career_field', 'hajj_umrah_target'] },
    { number: 45, slug: 'al-wasi', nameArabic: 'الْوَاسِعُ', transliteration: 'Al-Wasi', meaningId: 'Yang Mahaluas', theme: ['keluasan', 'rahmat', 'ilmu'], explanation: 'Al-Wasi adalah nama Allah yang menunjukkan keluasan-Nya yang meliputi segala sesuatu: luas rahmat-Nya, luas ilmu-Nya, luas karunia-Nya, dan luas kekuasaan-Nya. Tidak ada yang dapat membatasi-Nya.', dua: { arabic: 'يَا وَاسِعُ، وَسِّعْ عَلَيَّ رِزْقِي وَوَسِّعْ صَدْرِي وَوَسِّعْ لِي فِي دَارِي وَبَارِكْ لِي فِي أَهْلِي وَمَالِي وَعِلْمِي', transliteration: 'Ya Wasi, wassi alayya rizqi wa wassi sadri wa wassi li fi dari wa barik li fi ahli wa mali wa ilmi', translationId: 'Wahai Yang Mahaluas, lapangkanlah rezekiku, lapangkanlah dadaku, lapangkanlah rumahku, dan berkahilah keluargaku, hartaku, dan ilmuku.' }, evidence: [{ type: 'quran', reference: 'QS Al-Baqarah [2]: 115', arabic: 'إِنَّ اللَّهَ وَاسِعٌ عَلِيمٌ', translationId: 'Sesungguhnya Allah Mahaluas lagi Maha Mengetahui.', verificationStatus: 'sahih' }], personalPlaceholders: ['rizq_goal'] },
    { number: 46, slug: 'al-hakim', nameArabic: 'الْحَكِيمُ', transliteration: 'Al-Hakim', meaningId: 'Yang Mahabijaksana', theme: ['hikmah', 'kebijaksanaan', 'ketetapan'], explanation: 'Al-Hakim adalah nama Allah yang menunjukkan bahwa Dia Mahabijaksana dalam segala perbuatan dan ketetapan-Nya. Setiap yang Dia ciptakan, tetapkan, dan perintahkan mengandung hikmah yang sempurna.', dua: { arabic: 'يَا حَكِيمُ، أَلْهِمْنِي الْحِكْمَةَ فِي أَقْوَالِي وَأَفْعَالِي، وَاجْعَلْنِي رَاضِيًا بِحِكْمَتِكَ فِي كُلِّ مَا قَدَّرْتَهُ عَلَيَّ', transliteration: 'Ya Hakim, alhimnil-hikmata fi aqwali wa af-ali, waj-alni radiyan bihikmatika fi kulli ma qaddartahu alayy', translationId: 'Wahai Yang Mahabijaksana, ilhamkanlah kepadaku hikmah dalam ucapan dan perbuatanku, dan jadikanlah aku ridha dengan hikmah-Mu dalam segala yang Engkau takdirkan atasku.' }, evidence: [{ type: 'quran', reference: 'QS Al-Baqarah [2]: 269', arabic: 'يُؤْتِي الْحِكْمَةَ مَن يَشَاءُ وَمَن يُؤْتَ الْحِكْمَةَ فَقَدْ أُوتِيَ خَيْرًا كَثِيرًا', translationId: 'Dia memberikan hikmah kepada siapa yang Dia kehendaki. Dan barangsiapa diberi hikmah, sungguh ia telah diberi kebaikan yang banyak.', verificationStatus: 'sahih' }] },
    { number: 47, slug: 'al-wadud', nameArabic: 'الْوَدُودُ', transliteration: 'Al-Wadud', meaningId: 'Yang Maha Mencintai', theme: ['cinta', 'kasih-sayang', 'kedekatan'], explanation: 'Al-Wadud adalah nama Allah yang menunjukkan bahwa Dia Maha Mencintai hamba-hamba-Nya yang beriman dan bertakwa, dan Dia dicintai oleh mereka. Cinta-Nya adalah cinta yang sempurna, penuh kasih sayang dan kelembutan.', dua: { arabic: 'يَا وَدُودُ، اجْعَلْنِي مِنْ أَحْبَابِكَ وَأَوْلِيَائِكَ، وَاجْعَلْ حُبَّكَ أَحَبَّ إِلَيَّ مِنْ نَفْسِي وَأَهْلِي وَمَالِي وَمِنَ الْمَاءِ الْبَارِدِ', transliteration: 'Ya Wadud, ij-alni min ahbabika wa awliya-ik, waj-al hubbaka ahabba ilayya min nafsi wa ahli wa mali wa minal-ma-il-barid', translationId: 'Wahai Yang Maha Mencintai, jadikanlah aku termasuk orang-orang yang Engkau cintai dan wali-wali-Mu, dan jadikanlah cinta-Mu lebih aku cintai daripada diriku, keluargaku, hartaku, dan air yang dingin.' }, evidence: [{ type: 'quran', reference: 'QS Hud [11]: 90', arabic: 'إِنَّ رَبِّي رَحِيمٌ وَدُودٌ', translationId: 'Sesungguhnya Tuhanku Maha Penyayang lagi Maha Pencinta.', verificationStatus: 'sahih' }] },
    { number: 48, slug: 'al-majid', nameArabic: 'الْمَجِيدُ', transliteration: 'Al-Majid', meaningId: 'Yang Maha Mulia lagi Agung', theme: ['kemuliaan', 'keagungan', 'kemurahan'], explanation: 'Al-Majid adalah nama Allah yang menggabungkan antara kemuliaan, keagungan, dan kemurahan. Dia Maha Mulia dalam dzat-Nya, Maha Agung dalam sifat-sifat-Nya, dan Maha Pemurah dalam perbuatan-Nya.', dua: { arabic: 'يَا مَجِيدُ، أَسْأَلُكَ بِمَجْدِكَ الَّذِي مَلَأَ أَرْكَانَ عَرْشِكَ أَنْ تُمَجِّدَنِي بِطَاعَتِكَ وَأَنْ تَجْعَلَنِي مِنْ أَهْلِ الْمَجْدِ فِي الدُّنْيَا وَالْآخِرَةِ', transliteration: 'Ya Majid, as-aluka bimajdikal-ladzi mala-a arkana arsyika an tumajjidani bita-atika wa an taj-alani min ahlil-majdi fid-dunya wal-akhirah', translationId: 'Wahai Yang Maha Mulia lagi Agung, aku memohon kepada-Mu dengan kemuliaan-Mu yang memenuhi tiang-tiang Arsy-Mu agar Engkau memuliakanku dengan ketaatan kepada-Mu dan menjadikanku termasuk ahli kemuliaan di dunia dan akhirat.' }, evidence: [{ type: 'quran', reference: 'QS Hud [11]: 73', arabic: 'إِنَّهُ حَمِيدٌ مَّجِيدٌ', translationId: 'Sesungguhnya Dia Maha Terpuji lagi Maha Mulia.', verificationStatus: 'sahih' }] },
  ],
  matsurDuas: [
    { id: 'doa-cinta-allah', title: 'Doa Memohon Cinta Allah', source: 'HR Tirmidzi no. 3235', dua: { arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ حُبَّكَ وَحُبَّ مَنْ يُحِبُّكَ وَحُبَّ عَمَلٍ يُقَرِّبُنِي إِلَى حُبِّكَ', transliteration: 'Allahumma inni as-aluka hubbaka wa hubba man yuhibbuka wa hubba amalin yuqarribuni ila hubbik', translationId: 'Ya Allah, aku memohon kepada-Mu cinta-Mu, cinta orang yang mencintai-Mu, dan cinta amal yang mendekatkanku kepada cinta-Mu.' }, virtue: 'Doa yang diajarkan Nabi shallallahu alaihi wa sallam untuk memohon cinta Allah.' },
    { id: 'doa-kemuliaan', title: 'Doa Memohon Kemuliaan dari Allah', source: 'HR Muslim no. 2654', dua: { arabic: 'اللَّهُمَّ آتِ نَفْسِي تَقْوَاهَا وَزَكِّهَا أَنْتَ خَيْرُ مَنْ زَكَّاهَا أَنْتَ وَلِيُّهَا وَمَوْلَاهَا', transliteration: 'Allahumma ati nafsi taqwaha wa zakkiha anta khayru man zakkaha anta waliyyuha wa mawlaha', translationId: 'Ya Allah, berikanlah jiwaku ketakwaannya dan sucikanlah ia, Engkau sebaik-baik yang mensucikannya, Engkau pelindung dan penolongnya.' }, virtue: 'Doa pensucian jiwa yang diajarkan Nabi shallallahu alaihi wa sallam.' },
    { id: 'doa-hikmah', title: 'Doa Memohon Hikmah', source: 'QS Al-Baqarah [2]: 269', dua: { arabic: 'رَبِّ هَبْ لِي حُكْمًا وَأَلْحِقْنِي بِالصَّالِحِينَ', transliteration: 'Rabbi hab li hukman wa alhiqni bis-salihin', translationId: 'Ya Tuhanku, berikanlah kepadaku hikmah dan masukkanlah aku ke dalam golongan orang-orang yang saleh.' }, virtue: 'Doa Nabi Ibrahim alaihis salam memohon hikmah dan bergabung dengan orang-orang saleh.' },
    { id: 'doa-pengabulan', title: 'Doa Memohon Pengabulan Doa', source: 'HR Tirmidzi no. 3475', dua: { arabic: 'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ أَصْلِحْ لِي شَأْنِي كُلَّهُ وَلَا تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ', transliteration: 'Ya Hayyu ya Qayyumu birahmatika astaghitsu aslih li sya-ni kullahu wa la takilni ila nafsi tarfata ayn', translationId: 'Wahai Yang Maha Hidup, wahai Yang Maha Berdiri Sendiri, dengan rahmat-Mu aku memohon pertolongan, perbaikilah seluruh urusanku dan jangan serahkan aku kepada diriku sendiri walau sekejap mata.' }, virtue: 'Doa yang mengandung permohonan perbaikan seluruh urusan.' },
  ],
  closingDua: { arabic: 'اللَّهُمَّ يَا جَلِيلُ يَا كَرِيمُ يَا رَقِيبُ يَا مُجِيبُ يَا وَاسِعُ يَا حَكِيمُ يَا وَدُودُ يَا مَجِيدُ، أَكْرِمْنَا بِقُرْبِكَ وَأَجِبْ دُعَاءَنَا وَوَسِّعْ أَرْزَاقَنَا', transliteration: 'Allahumma ya Jalil ya Karim ya Raqib ya Mujib ya Wasi ya Hakim ya Wadud ya Majid, akrimna biqurbika wa ajib du-a-ana wa wassi arzaqana', translationId: 'Ya Allah, wahai Yang Maha Mulia, Yang Maha Pemurah, Yang Maha Mengawasi, Yang Maha Mengabulkan, Yang Mahaluas, Yang Mahabijaksana, Yang Maha Mencintai, Yang Maha Agung, muliakanlah kami dengan kedekatan-Mu, kabulkanlah doa kami, dan lapangkanlah rezeki kami.' },
  closingParagraph: 'Ya Allah, dengan 8 nama-Mu yang agung dalam fase ini—Al-Jalil, Al-Karim, Ar-Raqib, Al-Mujib, Al-Wasi, Al-Hakim, Al-Wadud, dan Al-Majid—aku memohon kemuliaan dan kedekatan dengan-Mu. Ya Allah, Engkau Al-Karim, karuniakanlah kepadaku rezeki 100 triliun rupiah yang halal dan berkah dari perbendaharaan-Mu yang tidak pernah habis. Ya Allah, Engkau Al-Mujib, kabulkanlah doaku untuk karier cybersecurity di Pekanbaru yang berkah dan bermanfaat. Ya Allah, Engkau Al-Wasi, lapangkanlah rezekiku dan lapangkanlah dadaku. Ya Allah, Engkau Al-Wadud, cintailah aku dan jadikanlah aku dicintai oleh hamba-hamba-Mu yang saleh. Ya Allah, sampaikan aku bersama istriku, orang tuaku, mertuaku, dan keluarga besarku untuk haji tahun 2026 bersama Ustadz Khalid Basalamah dan Ustadz Firanda Andirja. Aamiin ya Rabbal Aalamiin.',
};

export default part06;
