import { CollectionPartMetadata } from '@/types/asmaulHusna';

export const COLLECTION_INFO = {
  id: 'doa-komprehensif-asmaul-husna',
  title: 'Doa Komprehensif dengan 99 Asmaul Husna',
  description: 'Koleksi doa panjang berbasis 99 Asmaul Husna lengkap dengan doa ma\'tsur, dalil Al-Quran/Hadis, transliterasi, terjemahan, dan hajat dunia-akhirat. Dibagi menjadi 13 bagian untuk kemudahan membaca secara bertahap.',
  totalParts: 13,
  totalNames: 99,
  disclaimer: 'Doa susunan ini bukan lafaz ma\'tsur kecuali bagian yang diberi label Quran/Hadis. Konten disusun berdasarkan referensi ulama dan sumber yang tercantum.',
};

export const partsMetadata: CollectionPartMetadata[] = [
  {
    id: 'part-01-taubat',
    partNumber: 1,
    title: 'Pembukaan dan Taubat Total',
    phaseTitle: 'Fase 1: Taubat Total dan Pembersihan Hati',
    asmaRange: [1, 8],
    estimatedReadMinutes: 25,
    tags: ['taubat', 'rahmah', 'ampunan', 'pembersihan-hati'],
    status: 'full',
  },
  {
    id: 'part-02-ketenangan',
    partNumber: 2,
    title: 'Ketenangan Jiwa, Jalan Keluar & Rahmat',
    phaseTitle: 'Fase 2: Ketenangan Jiwa dan Jalan Keluar',
    asmaRange: [9, 16],
    estimatedReadMinutes: 22,
    tags: ['ketenangan', 'jalan-keluar', 'rahmat', 'sabar'],
    status: 'full',
  },
  {
    id: 'part-03-tawakkal',
    partNumber: 3,
    title: 'Tawakkal & Bersandar kepada Allah',
    phaseTitle: 'Fase 3: Tawakkal dan Rezeki',
    asmaRange: [17, 24],
    estimatedReadMinutes: 24,
    tags: ['tawakkal', 'rezeki', 'tawakal', 'kecukupan'],
    status: 'full',
  },
  {
    id: 'part-04-keagungan',
    partNumber: 4,
    title: 'Tunduk Kepada Keagungan Allah',
    phaseTitle: 'Fase 4: Tunduk Kepada Keagungan',
    asmaRange: [25, 32],
    estimatedReadMinutes: 23,
    tags: ['keagungan', 'kelembutan', 'keadilan', 'kesantunan'],
    status: 'full',
  },
  {
    id: 'part-05-mengagungkan',
    partNumber: 5,
    title: 'Mengagungkan Kebesaran Allah',
    phaseTitle: 'Fase 5: Mengagungkan Allah',
    asmaRange: [33, 40],
    estimatedReadMinutes: 22,
    tags: ['keagungan', 'ampunan', 'syukur', 'pemeliharaan'],
    status: 'full',
  },
  {
    id: 'part-06-kemuliaan',
    partNumber: 6,
    title: 'Memohon Kemuliaan & Kedekatan',
    phaseTitle: 'Fase 6: Memohon Kemuliaan',
    asmaRange: [41, 48],
    estimatedReadMinutes: 24,
    tags: ['kemuliaan', 'kedekatan', 'cinta', 'kemurahan'],
    status: 'full',
  },
  {
    id: 'part-07-keesaan',
    partNumber: 7,
    title: 'Bersaksi Keesaan Allah',
    phaseTitle: 'Fase 7: Bersaksi Keesaan dan Kebenaran',
    asmaRange: [49, 56],
    estimatedReadMinutes: 22,
    tags: ['tauhid', 'keesaan', 'kebenaran', 'tawakal'],
    status: 'full',
  },
  {
    id: 'part-08-ilmu',
    partNumber: 8,
    title: 'Mengenal Ilmu Allah',
    phaseTitle: 'Fase 8: Ilmu dan Pengetahuan Allah',
    asmaRange: [57, 64],
    estimatedReadMinutes: 20,
    tags: ['ilmu', 'pengetahuan', 'hikmah', 'kebenaran'],
    status: 'stub',
  },
  {
    id: 'part-09-keagungan2',
    partNumber: 9,
    title: 'Mengakui Keagungan Allah',
    phaseTitle: 'Fase 9: Refleksi Mendalam',
    asmaRange: [65, 72],
    estimatedReadMinutes: 20,
    tags: ['keagungan', 'refleksi', 'pengakuan', 'kebesaran'],
    status: 'stub',
  },
  {
    id: 'part-10-kebaikan',
    partNumber: 10,
    title: 'Memohon Kebaikan',
    phaseTitle: 'Fase 10: Kebaikan dan Keindahan',
    asmaRange: [73, 80],
    estimatedReadMinutes: 20,
    tags: ['kebaikan', 'keindahan', 'pemberian', 'perlindungan'],
    status: 'stub',
  },
  {
    id: 'part-11-keadilan',
    partNumber: 11,
    title: 'Memohon Keadilan',
    phaseTitle: 'Fase 11: Keadilan dan Perlindungan',
    asmaRange: [81, 88],
    estimatedReadMinutes: 20,
    tags: ['keadilan', 'perlindungan', 'pembalasan', 'keamanan'],
    status: 'stub',
  },
  {
    id: 'part-12-kecukupan',
    partNumber: 12,
    title: 'Memohon Kecukupan',
    phaseTitle: 'Fase 12: Kecukupan dan Petunjuk',
    asmaRange: [89, 96],
    estimatedReadMinutes: 20,
    tags: ['kecukupan', 'petunjuk', 'kesabaran', 'keabadian'],
    status: 'stub',
  },
  {
    id: 'part-13-penyerahan',
    partNumber: 13,
    title: 'Penyerahan Diri Total',
    phaseTitle: 'Fase 13: Penutup Agung',
    asmaRange: [97, 99],
    estimatedReadMinutes: 15,
    tags: ['penyerahan', 'penutup', 'husnul-khatimah', 'keabadian'],
    status: 'stub',
  },
];
