import { CollectionPartMetadata } from '@/types/asmaulHusna';

export const COLLECTION_INFO = {
  id: 'doa-komprehensif-asmaul-husna',
  title: 'Doa Komprehensif dengan 99 Asmaul Husna',
  description: 'Koleksi doa panjang berbasis 99 Asmaul Husna lengkap dengan doa ma\'tsur, dalil Al-Quran/Hadis, transliterasi, terjemahan, dan hajat dunia-akhirat. Dibagi menjadi 13 bagian untuk kemudahan membaca secara bertahap.',
  totalParts: 13,
  totalNames: 99,
  disclaimer: 'Doa susunan ini bukan lafaz ma\'tsur kecuali bagian yang diberi label Quran/Hadis. Konten disusun berdasarkan referensi ulama dan sumber yang tercantum.',
};

export const partsMetadata: CollectionPartMetadata[] = [
  {
    id: 'part-01-taubat',
    partNumber: 1,
    title: 'Pembukaan dan Taubat Total',
    phaseTitle: 'Fase 1: Taubat Total dan Pembersihan Hati',
    asmaRange: [1, 8],
    estimatedReadMinutes: 25,
    tags: ['taubat', 'rahmah', 'ampunan', 'pembersihan-hati'],
    status: 'full',
  },
  {
    id: 'part-02-ketenangan',
    partNumber: 2,
    title: 'Ketenangan Jiwa, Jalan Keluar & Rahmat',
    phaseTitle: 'Fase 2: Ketenangan Jiwa dan Jalan Keluar',
    asmaRange: [9, 16],
    estimatedReadMinutes: 22,
    tags: ['ketenangan', 'jalan-keluar', 'rahmat', 'sabar'],
    status: 'full',
  },
  {
    id: 'part-03-tawakkal',
    partNumber: 3,
    title: 'Tawakkal & Bersandar kepada Allah',
    phaseTitle: 'Fase 3: Tawakkal dan Rezeki',
    asmaRange: [17, 24],
    estimatedReadMinutes: 24,
    tags: ['tawakkal', 'rezeki', 'tawakal', 'kecukupan'],
    status: 'full',
  },
  {
    id: 'part-04-keagungan',
    partNumber: 4,
    title: 'Tunduk Kepada Keagungan Allah',
    phaseTitle: 'Fase 4: Tunduk Kepada Keagungan',
    asmaRange: [25, 32],
    estimatedReadMinutes: 23,
    tags: ['keagungan', 'kelembutan', 'keadilan', 'kesantunan'],
    status: 'full',
  },
  {
    id: 'part-05-mengagungkan',
    partNumber: 5,
    title: 'Mengagungkan Kebesaran Allah',
    phaseTitle: 'Fase 5: Mengagungkan Allah',
    asmaRange: [33, 40],
    estimatedReadMinutes: 22,
    tags: ['keagungan', 'ampunan', 'syukur', 'pemeliharaan'],
    status: 'full',
  },
  {
    id: 'part-06-kemuliaan',
    partNumber: 6,
    title: 'Memohon Kemuliaan & Kedekatan',
    phaseTitle: 'Fase 6: Memohon Kemuliaan',
    asmaRange: [41, 48],
    estimatedReadMinutes: 24,
    tags: ['kemuliaan', 'kedekatan', 'cinta', 'kemurahan'],
    status: 'full',
  },
  {
    id: 'part-07-keesaan',
    partNumber: 7,
    title: 'Bersaksi Keesaan Allah',
    phaseTitle: 'Fase 7: Bersaksi Keesaan dan Kebenaran',
    asmaRange: [49, 56],
    estimatedReadMinutes: 22,
    tags: ['tauhid', 'keesaan', 'kebenaran', 'tawakal'],
    status: 'full',
  },
  {
    id: 'part-08-kuasa-hidup-mati',
    partNumber: 8,
    title: 'Kuasa atas Hidup dan Mati',
    phaseTitle: 'Fase 8: Mengenal Kuasa Allah atas Hidup dan Mati',
    asmaRange: [57, 63],
    estimatedReadMinutes: 20,
    tags: ['ilmu', 'pengawasan', 'penciptaan', 'kehidupan', 'kematian'],
    status: 'full',
  },
  {
    id: 'part-09-kemuliaan-keagungan',
    partNumber: 9,
    title: 'Kemuliaan dan Keagungan',
    phaseTitle: 'Fase 9: Mengenal Kemuliaan dan Keagungan Allah',
    asmaRange: [64, 70],
    estimatedReadMinutes: 20,
    tags: ['kemuliaan', 'keagungan', 'tauhid', 'kekuasaan'],
    status: 'full',
  },
  {
    id: 'part-10-keabadian-keluhuran',
    partNumber: 10,
    title: 'Keabadian dan Keluhuran',
    phaseTitle: 'Fase 10: Mengenal Keabadian dan Keluhuran Allah',
    asmaRange: [71, 77],
    estimatedReadMinutes: 20,
    tags: ['keabadian', 'keluhuran', 'kedermawanan', 'sifat dzat'],
    status: 'full',
  },
  {
    id: 'part-11-taubat-pengampunan',
    partNumber: 11,
    title: 'Taubat dan Pengampunan',
    phaseTitle: 'Fase 11: Memohon Taubat dan Pengampunan Allah',
    asmaRange: [78, 84],
    estimatedReadMinutes: 20,
    tags: ['taubat', 'pengampunan', 'keadilan', 'keagungan'],
    status: 'full',
  },
  {
    id: 'part-12-perkumpulan-kekayaan',
    partNumber: 12,
    title: 'Perkumpulan dan Kekayaan',
    phaseTitle: 'Fase 12: Mengenal Allah Yang Maha Mengumpulkan dan Maha Kaya',
    asmaRange: [85, 91],
    estimatedReadMinutes: 20,
    tags: ['kekayaan', 'kecukupan', 'perlindungan', 'cahaya'],
    status: 'full',
  },
  {
    id: 'part-13-penutup-keabadian',
    partNumber: 13,
    title: 'Penutup dan Keabadian',
    phaseTitle: 'Fase 13: Penutup Doa dengan Nama-Nama Keabadian',
    asmaRange: [92, 99],
    estimatedReadMinutes: 25,
    tags: ['hidayah', 'keabadian', 'kesabaran', 'penutup'],
    status: 'full',
  },
];
